[package]
name = "gba-workspace"
version = "0.1.0"
description = "GBA Workspace"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
tauri = { version = "2.12.2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
