[package]
name = "gba-workspace"
version = "1.5.500"
description = "Workspace"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
tauri = { version = "2.12.2", features = [] }
tauri-plugin-updater = { version = "=2.13.2" }
tauri-plugin-process = { version = "=2.4.0" }
serde_json = "=1.0.151"
minisign-verify = "=0.2.5"
base64 = "=0.23.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
