import assert from 'node:assert/strict';
import fs from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
const db = new PGlite();
let checks=0;
const ok=(actual,expected)=>{assert.deepEqual(actual,expected);checks++;};
const reject=async(promise,pattern)=>{await assert.rejects(promise,pattern);checks++;};
const scalar=async(sql,args=[])=>Object.values((await db.query(sql,args)).rows[0])[0];
const ids={owner:'00000000-0000-0000-0000-000000000001',guest:'00000000-0000-0000-0000-000000000002',admin:'00000000-0000-0000-0000-000000000003'};
const actor=async key=>{await db.exec('reset role');await db.query("select set_config('test.uid',$1,false)",[ids[key]||'']);await db.exec('set role authenticated');};
const migrate=async suffix=>db.exec(fs.readFileSync('supabase/migrations/'+fs.readdirSync('supabase/migrations').find(name=>name.endsWith(suffix)),'utf8'));
try {
  await db.exec(`create role anon;create role authenticated;create schema auth;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create table usuarios(id uuid primary key,nombre text,rol text,nombre_publico text,perfil_publico boolean default true);
create table notificaciones(id uuid default gen_random_uuid(),usuario_id uuid,actor_id uuid,tipo text,titulo text,mensaje text,action_url text,target_type text,target_id uuid,leida boolean default false);
create function vista_is_platform_admin() returns boolean language sql stable security definer set search_path=public,pg_temp as $$select exists(select 1 from usuarios where id=auth.uid() and rol in('Dueño','Admin'))$$;
create function vista_editorial_slugify(value text) returns text language sql as $$select regexp_replace(lower(value),'[^a-z0-9]+','-','g')$$;
create table contenido(id uuid primary key default gen_random_uuid(),titulo text,categoria text,estado_publicacion text,created_at timestamptz default now(),publicar_at timestamptz,vistas bigint default 0);
create table vistas_usuario(usuario_id uuid,contenido_id uuid,created_at timestamptz default now(),primary key(usuario_id,contenido_id));`);
  for(const [key,id] of Object.entries(ids))await db.query('insert into usuarios(id,nombre,rol) values($1,$2,$3)',[id,key,key==='admin'?'Dueño':'Ciudadano']);
  await migrate('_network_server_partners_pilot.sql');
  await migrate('_network_development_studios.sql');
  await migrate('_network_account_access.sql');
  // Exercise the actual authenticated content view writer as well as ranking.
  const views=fs.readFileSync('supabase/migrations/202608140005_authenticated_engagement_network_editorial.sql','utf8');
  await db.exec(views.slice(0,views.indexOf('-- Retire')).replace('begin;', '', 1));
  await migrate('_home_discovery_partners.sql');
  await db.exec('set role anon');await reject(scalar('select vista_home_discovery()'),/permission denied/);
  await actor(null);await reject(scalar('select vista_home_discovery()'),/Authentication required/);
  await actor('owner');ok(await scalar('select vista_home_discovery()'),{partners:[],ranking:[]});
  const server=await scalar('select to_jsonb(vista_save_network_server(null,$1))',[{nombre:'Servidor con estudio',descripcion:'Una comunidad para probar el ranking de VISTA.',ip:'play.example.invalid'}]);
  await actor('admin');await scalar("select vista_review_network_server($1,'aprobado',false,'Notas privadas')",[server.id]);
  const agreement={placement:'hero',state:'active',starts_at:new Date(Date.now()-86400000).toISOString(),ends_at:new Date(Date.now()+86400000).toISOString(),amount:1,currency:'USD',payment_confirmed:true,deliverables:'Una promoción de prueba para verificar Inicio.',hero_video_url:'https://example.com/video.mp4'};
  const partner=await scalar('select to_jsonb(vista_save_network_partner(null,$1,$2))',[server.id,agreement]);
  ok(partner.home_enabled,false);ok((await scalar('select vista_home_discovery()')).partners.length,0);
  await reject(scalar('select to_jsonb(vista_save_network_partner($1,$2,$3))',[partner.id,server.id,{...agreement,home_enabled:true,placement:'directory'}]),/Home requires/);
  await reject(scalar('select to_jsonb(vista_save_network_partner($1,$2,$3))',[partner.id,server.id,{...agreement,hero_video_url:'javascript:alert(1)'}]),/HTTPS/);
  await scalar('select to_jsonb(vista_save_network_partner($1,$2,$3))',[partner.id,server.id,{...agreement,home_enabled:true}]);
  const published=(await scalar('select vista_home_discovery()')).partners[0];
  ok(published.partner.hero_video_url,agreement.hero_video_url);
  for(const key of ['amount','payment_confirmed','created_by','deliverables'])ok(key in published.partner,false);
  for(const key of ['owner_id','review_notes'])ok(key in published.server,false);
  await actor('guest');await reject(scalar('select to_jsonb(vista_save_network_partner($1,$2,$3))',[partner.id,server.id,agreement]),/Platform admin/);
  await scalar("select vista_track_network_event($1,'hero_view','hero',$2)",[server.id,partner.id]);
  await scalar("select vista_track_network_event($1,'directory_view','directory')",[server.id]);
  ok((await scalar('select vista_home_discovery()')).ranking.length,0);
  await scalar("select vista_track_network_event($1,'profile_view','profile')",[server.id]);
  await db.exec('reset role');
  // Same GBA ID on a later day still contributes one distinct visitor.
  await db.query("insert into network_server_events(server_id,user_id,event,source,event_day) values($1,$2,'profile_view','profile',current_date-1)",[server.id,ids.guest]);
  const insert=async(category,state='aprobado',schedule=null)=>scalar('insert into contenido(titulo,categoria,estado_publicacion,publicar_at) values($1,$2,$3,$4) returning id',[category+' de prueba',category,state,schedule]);
  const video=await insert('Tutorial');const newspaper=await insert('Periódico');const pending=await insert('Película','pendiente');const scheduled=await insert('Original','aprobado',new Date(Date.now()+86400000));const unknown=await insert('Desconocido');const untouched=await insert('Guía');
  await actor('guest');ok(await scalar('select vista_register_content_view($1)',[video]),true);ok(await scalar('select vista_register_content_view($1)',[video]),false);ok(await scalar('select vista_register_content_view($1)',[pending]),false);
  await scalar('select vista_register_content_view($1)',[newspaper]);
  await actor('owner');await scalar('select vista_register_content_view($1)',[video]);
  await db.exec('reset role');
  for(const id of [pending,scheduled,unknown])for(const user of Object.values(ids))await db.query('insert into vistas_usuario(usuario_id,contenido_id) values($1,$2)',[user,id]);
  // Legacy aggregate counters never manufacture a first place.
  await db.query('update contenido set vistas=9999 where id=$1',[untouched]);
  await actor('guest');const ranking=(await scalar('select vista_home_discovery()')).ranking;
  ok(ranking.length,3);ok(ranking[0].id,video);ok(ranking[0].reach,2);ok(ranking.find(x=>x.id===server.id).reach,1);ok(ranking.some(x=>x.kind==='newspaper'),true);
  ok(ranking.some(x=>[pending,scheduled,unknown,untouched].includes(x.id)),false);
  for(const entry of ranking)ok('usuario_id' in entry,false);
  await db.exec('reset role');for(let i=0;i<15;i++){const id=await insert('Tutorial');await db.query('insert into vistas_usuario(usuario_id,contenido_id) values($1,$2)',[ids.owner,id]);}
  await actor('guest');ok((await scalar('select vista_home_discovery()')).ranking.length,10);
  await actor('admin');await scalar('select to_jsonb(vista_save_network_partner($1,$2,$3))',[partner.id,server.id,{...agreement,home_enabled:true,state:'paused'}]);
  ok((await scalar('select vista_home_discovery()')).partners.length,0);
  await scalar('select to_jsonb(vista_save_network_partner($1,$2,$3))',[partner.id,server.id,{...agreement,home_enabled:true,starts_at:new Date(Date.now()-86400000*3),ends_at:new Date(Date.now()-86400000)}]);
  ok((await scalar('select vista_home_discovery()')).partners.length,0);
  await scalar("select vista_review_network_server($1,'suspendido',false,'')",[server.id]);
  ok((await scalar('select vista_home_discovery()')).ranking.some(x=>x.id===server.id),false);
  console.log(`Home: ${checks} assertions passed (mixed ranking, distinct GBA ID visits, paid placement, privacy and moderation).`);
} finally { await db.close(); }
