import assert from 'node:assert/strict';
import { toNativeVersion, displayVersion, newerNative } from '../src/workspace/releaseVersion.mjs';
import { createUpdateController } from '../src/workspace/updateController.mjs';
assert.equal(toNativeVersion('0.1.4.1'),'0.1.401');
assert.equal(displayVersion('0.1.401'),'0.1.4.1');
assert.equal(displayVersion('0.1.4'),'0.1.4');
assert.ok(newerNative(toNativeVersion('0.1.4.1'),'0.1.4'));
assert.ok(newerNative(toNativeVersion('0.1.4.2'),toNativeVersion('0.1.4.1')));
assert.ok(newerNative(toNativeVersion('0.1.5'),toNativeVersion('0.1.4.99')));
assert.throws(()=>toNativeVersion('0.1.4.100'));
let downloaded=0, installed=0, cached=null;
const storage={getItem:()=>cached,setItem:(_,value)=>{cached=value;}};
const update={version:'0.1.401',rawJson:{minimumNativeVersion:'0.1.401',mandatory:true},close:async()=>{},download:async()=>{downloaded++;},install:async()=>{installed++;}};
const controller=createUpdateController({check:async()=>update,currentVersion:async()=> '0.1.4',storage,relaunch:async()=>{}});
await controller.check();
assert.equal(controller.getState().required,true);
assert.equal(controller.getState().version,'0.1.4.1');
assert.equal(cached,'0.1.401');
assert.equal(downloaded+installed,0,'Required updates still require explicit installation');
await controller.download();await controller.install();assert.equal(installed,1);
const offline=createUpdateController({check:async()=>{throw Error('Offline');},currentVersion:async()=> '0.1.4',storage,relaunch:async()=>{}});
await offline.check();assert.equal(offline.getState().required,true,'An offline retry cannot bypass a known minimum');
const current=createUpdateController({check:async()=>null,currentVersion:async()=> '0.1.401',storage,relaunch:async()=>{}});
await current.check();assert.equal(current.getState().required,false);
cached=null;
const inUse=createUpdateController({check:async()=>update,currentVersion:async()=> '0.1.4',storage,relaunch:async()=>{}});
await inUse.check({deferRequirement:true});assert.equal(inUse.getState().required,false,'A periodic check does not unmount active work');assert.equal(inUse.getState().mandatoryAvailable,true);
const nextStart=createUpdateController({check:async()=>update,currentVersion:async()=> '0.1.4',storage,relaunch:async()=>{}});
await nextStart.check();assert.equal(nextStart.getState().required,true);
const invalid=createUpdateController({check:async()=>({...update,rawJson:{minimumNativeVersion:'0.1.999'}}),currentVersion:async()=> '0.1.401',relaunch:async()=>{}});
await invalid.check();assert.equal(invalid.getState().phase,'error');
console.log('PASS: maintenance numbering, legacy upgrade ordering, pre-login mandatory updates, manual installation, offline enforcement and preservation of active work.');

assert.equal(toNativeVersion('1.5.0'),'1.5.0');
assert.equal(toNativeVersion('1.5.0.1'),'1.5.1');
assert.equal(displayVersion('1.5.1'),'1.5.0.1');
assert.ok(newerNative(toNativeVersion('1.5.0.1'),toNativeVersion('1.5.0')));
assert.ok(newerNative(toNativeVersion('1.6.0'),toNativeVersion('1.5.0.99')));
