import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { PGlite } from '@electric-sql/pglite';

const root=process.argv[2]||process.cwd();
const migration=fs.readdirSync(path.join(root,'supabase/migrations')).find(name=>name.endsWith('_network_server_partners_pilot.sql'));
const db=new PGlite();
let checks=0;
const ok=(value,expected)=>{assert.deepEqual(value,expected);checks++;};
const ids={owner:'00000000-0000-0000-0000-000000000001',outsider:'00000000-0000-0000-0000-000000000002',admin:'00000000-0000-0000-0000-000000000003',manager:'00000000-0000-0000-0000-000000000004'};
const actor=async who=>{await db.exec('reset role');await db.query("select set_config('test.uid',$1,false)",[who?ids[who]:'']);await db.exec('set role authenticated');};
const scalar=async(sql,args=[])=>{const result=await db.query(sql,args);return Object.values(result.rows[0])[0];};
const rejects=async(promise,match)=>{await assert.rejects(promise,match);checks++;};
try{
  await db.exec(`create role anon;create role authenticated;create schema auth;
    create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
    create table public.usuarios(id uuid primary key,nombre text,rol text);
    create function public.vista_is_platform_admin() returns boolean language sql stable security definer set search_path=public,pg_temp as $$select exists(select 1 from usuarios where id=auth.uid() and rol in('Dueño','Admin'))$$;
    create function public.vista_editorial_slugify(value text) returns text language sql as $$select regexp_replace(lower(value),'[^a-z0-9]+','-','g')$$;
    insert into usuarios values('${ids.owner}','owner','Ciudadano'),('${ids.outsider}','outsider','Ciudadano'),('${ids.admin}','admin','Dueño'),('${ids.manager}','manager','Ciudadano');
    create table public.network_businesses(note text);insert into public.network_businesses values('Legacy business');
    create table public.newspaper_archive(body text);insert into public.newspaper_archive values('Periódico sobre Empyria');`);
  await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',migration),'utf8'));
  await actor(null);
  await rejects(scalar('select vista_network_directory()'),/Authentication required/);
  await actor('owner');
  const payload={nombre:'Atlas de prueba',descripcion:'Comunidad de prueba de naciones, comercio y diplomacia.',ip:'play.example.invalid',edition:'java',idioma:'Español',estilo:'Naciones',estado:'aprobado',verificada:true};
  const server=await scalar('select to_jsonb(vista_save_network_server(null,$1))',[payload]);
  ok(server.estado,'pendiente');ok(server.verificada,false);ok(server.owner_id,ids.owner);
  ok((await scalar('select vista_network_directory()')).servers.length,0);
  ok((await scalar('select vista_my_network_servers()')).length,1);
  await rejects(scalar('select vista_save_network_server(null,$1)',[{...payload,nombre:'Unsafe',website_url:'javascript:alert(1)'}]),/HTTPS/);
  await rejects(scalar('select vista_save_network_server(null,$1)',[{...payload,nombre:'Empty',ip:'',discord_url:''}]),/address or Discord/);
  await rejects(scalar('select vista_review_network_server($1,\'aprobado\',true,\'\')',[server.id]),/Platform admin/);
  await actor('outsider');
  await rejects(scalar('select vista_save_network_server($1,$2)',[server.id,payload]),/manager access/);
  await rejects(scalar('select vista_network_team($1)',[server.id]),/manager access/);
  await rejects(scalar("select vista_network_report($1,now()-interval '7 days',now())",[server.id]),/manager access/);
  await rejects(scalar("select vista_track_network_event($1,'profile_view','profile')",[server.id]),/Approved server/);
  await actor('owner');
  await scalar("select vista_manage_network_member($1,'@manager',false)",[server.id]);
  ok((await scalar('select vista_network_team($1)',[server.id])).length,2);
  await actor('manager');ok((await scalar('select vista_my_network_servers()')).length,1);
  await rejects(scalar("select vista_manage_network_member($1,'outsider',false)",[server.id]),/owner access/);
  await actor('owner');await scalar("select vista_manage_network_member($1,'manager',true)",[server.id]);
  await actor('manager');ok((await scalar('select vista_my_network_servers()')).length,0);
  await actor('admin');await scalar("select vista_review_network_server($1,'aprobado',true,'')",[server.id]);
  await actor('owner');await scalar("select vista_request_network_partner($1,'both')",[server.id]);
  ok((await scalar('select vista_my_network_servers()'))[0].partner_interest,'both');
  const published=(await scalar('select vista_network_directory()')).servers[0];
  ok(published.verificada,true);ok('owner_id' in published,false);ok('review_notes' in published,false);ok('partner_interest' in published,false);
  const agreement={placement:'both',state:'active',starts_at:new Date(Date.now()-86400000).toISOString(),ends_at:new Date(Date.now()+86400000).toISOString(),amount:10,currency:'USD',payment_confirmed:true,deliverables:'Hero y directorio por un periodo de prueba.',hero_title:'Una comunidad de prueba'};
  await rejects(scalar('select to_jsonb(vista_save_network_partner(null,$1,$2))',[server.id,agreement]),/Platform admin/);
  await actor('admin');
  await rejects(scalar('select to_jsonb(vista_save_network_partner(null,$1,$2))',[server.id,{...agreement,payment_confirmed:false}]),/check constraint/);
  await rejects(scalar('select to_jsonb(vista_save_network_partner(null,$1,$2))',[server.id,{...agreement,amount:0}]),/check constraint/);
  const partner=await scalar('select to_jsonb(vista_save_network_partner(null,$1,$2))',[server.id,agreement]);
  let directory=await scalar('select vista_network_directory()');ok(directory.partners.length,1);ok('amount' in directory.partners[0],false);ok('payment_confirmed' in directory.partners[0],false);
  await actor('outsider');
  await scalar("select vista_track_network_event($1,'hero_view','hero',$2)",[server.id,partner.id]);
  await scalar("select vista_track_network_event($1,'hero_view','hero',$2)",[server.id,partner.id]);
  await scalar("select vista_track_network_event($1,'copy_ip','profile',$2)",[server.id,partner.id]);
  await rejects(scalar("select vista_track_network_event($1,'hero_view','hero')",[server.id]),/active Partner/);
  await rejects(scalar("select vista_track_network_event($1,'profile_view','hero',$2)",[server.id,partner.id]),/Invalid event/);
  await actor('owner');const report=await scalar("select vista_network_report($1,now()-interval '7 days',now()+interval '1 day',$2)",[server.id,partner.id]);ok(report.hero_views,1);ok(report.copy_ip,1);ok(report.people,1);
  await actor('admin');
  await scalar('select to_jsonb(vista_save_network_partner($1,$2,$3))',[partner.id,server.id,{...agreement,state:'paused'}]);ok((await scalar('select vista_network_directory()')).partners.length,0);
  await scalar('select to_jsonb(vista_save_network_partner($1,$2,$3))',[partner.id,server.id,{...agreement,starts_at:new Date(Date.now()+86400000).toISOString(),ends_at:new Date(Date.now()+2*86400000).toISOString()}]);ok((await scalar('select vista_network_directory()')).partners.length,0);
  await scalar('select to_jsonb(vista_save_network_partner($1,$2,$3))',[partner.id,server.id,{...agreement,starts_at:new Date(Date.now()-2*86400000).toISOString(),ends_at:new Date(Date.now()-86400000).toISOString()}]);ok((await scalar('select vista_network_directory()')).partners.length,0);
  await scalar('select to_jsonb(vista_save_network_partner($1,$2,$3))',[partner.id,server.id,agreement]);
  await scalar('select to_jsonb(vista_save_network_partner(null,$1,$2))',[server.id,agreement]);
  await scalar('select to_jsonb(vista_save_network_partner(null,$1,$2))',[server.id,agreement]);
  await rejects(scalar('select to_jsonb(vista_save_network_partner(null,$1,$2))',[server.id,agreement]),/three hero slots/);
  await scalar("select vista_review_network_server($1,'suspendido',true,'Pausa')",[server.id]);ok((await scalar('select vista_network_directory()')).partners.length,0);
  await actor('owner');await scalar('select to_jsonb(vista_save_network_server($1,$2))',[server.id,payload]);ok((await scalar('select vista_my_network_servers()'))[0].estado,'suspendido');
  await actor('admin');await scalar("select vista_review_network_server($1,'aprobado',true,'')",[server.id]);
  await actor('owner');await scalar('select to_jsonb(vista_save_network_server($1,$2))',[server.id,{...payload,headline:'Texto modificado'}]);ok((await scalar('select vista_my_network_servers()'))[0].estado,'pendiente');
  await db.exec('reset role');
  ok(await scalar('select count(*)::int from public.network_businesses'),1);ok(await scalar('select body from public.newspaper_archive'),'Periódico sobre Empyria');
  ok(await scalar("select count(*)::int from pg_class where relname in ('network_servers','network_server_members','network_partner_agreements','network_server_events') and relrowsecurity"),4);
  const functions=(await db.query("select oid::regprocedure::text as signature from pg_proc where pronamespace='public'::regnamespace and proname in ('vista_network_directory','vista_my_network_servers','vista_save_network_server','vista_request_network_partner','vista_network_team','vista_manage_network_member','vista_admin_network','vista_review_network_server','vista_save_network_partner','vista_track_network_event','vista_network_report')")).rows;
  for(const {signature}of functions){ok(await scalar("select has_function_privilege('anon',$1,'execute')",[signature]),false);}
  for(const table of ['network_servers','network_server_members','network_partner_agreements','network_server_events']){
    ok(await scalar("select has_table_privilege('anon',$1,'select')",[table]),false);
    ok(await scalar("select has_table_privilege('authenticated',$1,'select')",[table]),false);
  }
  console.log(`PASS: ${checks} assertions for authentication, moderation, membership, scoped reports, sponsorship payment and expiry, hero capacity, event deduplication and legacy preservation.`);
}catch(error){console.error(error.message);if(error.query)console.error(error.query);process.exitCode=1;}finally{await db.close();}
