import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { buildReleaseManifest } from '../scripts/workspace-release-manifest.mjs';
const bytes=Buffer.alloc(100000,1),sha256=createHash('sha256').update(bytes).digest('hex');
const commit='a'.repeat(40);
const proof={commit,evidenceUrl:'https://github.com/example/app/releases/tag/v1',backupRestoreVerified:true,stagingAuthVerified:true,gatewayVerified:true,membershipRlsVerified:true,activationExpiryRevocationVerified:true,installedMacosVerified:true,installedWindowsVerified:true};
const packages={commit,downloads:[{platform:'macos',architecture:'aarch64',version:'0.1.0',url:'https://example.com/app.dmg',sha256,size:bytes.length,signing:'ad-hoc'},{platform:'windows',architecture:'x86_64',version:'0.1.0',url:'https://example.com/app.exe',sha256,size:bytes.length,signing:'unsigned'}]};
const fetchAsset=async url=>({ok:true,url:String(url),arrayBuffer:async()=>bytes});
await assert.rejects(buildReleaseManifest(packages,proof,fetchAsset),/signing/);
await assert.rejects(buildReleaseManifest(packages,{...proof,channel:'beta'},fetchAsset),/authorization/);
const beta={...proof,channel:'beta',betaDistributionAuthorized:true};
assert.equal((await buildReleaseManifest(packages,beta,fetchAsset)).channel,'beta');
await assert.rejects(buildReleaseManifest(packages,{...beta,installedWindowsVerified:false},fetchAsset),/installedWindowsVerified/);
await assert.rejects(buildReleaseManifest(packages,{...beta,commit:'b'.repeat(40)},fetchAsset),/commit/);
await assert.rejects(buildReleaseManifest(packages,beta,async url=>({ok:true,url:String(url),arrayBuffer:async()=>Buffer.alloc(100000,2)})),/differs/);
await assert.rejects(buildReleaseManifest({...packages,downloads:[...packages.downloads,packages.downloads[0]]},beta,fetchAsset),/Duplicate/);
await assert.rejects(buildReleaseManifest({...packages,downloads:packages.downloads.map(p=>({...p,url:p.url+'?token=private'}))},beta,fetchAsset),/permanent/);
const signed={...packages,downloads:packages.downloads.map(p=>({...p,signing:p.platform==='macos'?'notarized':'authenticode'}))};
assert.equal((await buildReleaseManifest(signed,proof,fetchAsset)).channel,'stable');
console.log('PASS: stable signatures retained, beta authorization, installed acceptance, exact commit and public asset integrity.');
