import assert from 'node:assert/strict';
import fs from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
import { creditPayload, notificationLink, contentLink } from '../src/utils/social.js';

const db = new PGlite(); let checks=0;
const ok=(a,b)=>{ assert.deepEqual(a,b); checks++; };
const rejects=async(p,re)=>{ await assert.rejects(p,re); checks++; };
const scalar=async(sql,args=[])=>Object.values((await db.query(sql,args)).rows[0])[0];
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const owner=id(1), contributor=id(2), stranger=id(3), admin=id(4), hidden=id(5), video=id(10), draft=id(11), business=id(12), keynote=id(13), update=id(14);
const actor=async(user)=>{await db.exec('reset role');await db.query("select set_config('test.uid',$1,false)",[user||'']);await db.exec('set role authenticated');};
const inspect=async(sql,args=[])=>{await db.exec('reset role');const result=await scalar(sql,args);await db.exec('set role authenticated');return result;};
const save=credits=>db.query('select vista_replace_credits($1,$2,$3)', ['content',video,credits]);
const credit={role:'Tutorial',handle:'@creator',display_name:'Creator',verified:true,contributor_id:contributor};
const fn=(source,name)=>source.match(new RegExp('create or replace function public\\.'+name+'\\([\\s\\S]*?\\n\\$\\$;'))[0];
try {
  ok(creditPayload([{...credit,id:id(99)}])[0].id,id(99));
  ok(creditPayload([{role:'Guion',display_name:'Externo'}])[0].external,true);
  for(const value of [[{...credit,role:''}],[{...credit,verified:false}],[credit,credit],Array(31).fill(credit),[{...credit,display_name:'x'}]]) {
    assert.throws(()=>creditPayload(value)); checks++;
  }
  ok(notificationLink({target_type:'content',target_id:video,action_url:`/?edition=${video}`}),contentLink(video));
  ok(notificationLink({contenido_id:video}),contentLink(video));
  ok(notificationLink({target_type:'update',target_id:update,action_url:'/'}),`/?update=${update}`);
  ok(notificationLink({action_url:'//example.com'}),'/');
  ok(notificationLink({action_url:'https://example.com'}),'/');
  await db.exec(`create role anon; create role authenticated; create schema auth; grant usage on schema auth to anon,authenticated;
    create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
    create table public.usuarios(id uuid primary key,nombre text,nombre_publico text,perfil_publico boolean default true,bio text,avatar_url text,servidor text,nacion text,rol text,sello_editorial text);
    insert into public.usuarios(id,nombre) values('${owner}','owner'),('${contributor}','creator'),('${stranger}','stranger'),('${admin}','admin'),('${hidden}','hidden');
    update public.usuarios set perfil_publico=false where id='${hidden}';
    create table public.editoriales(id uuid primary key);
    create table public.contenido(id uuid primary key,autor_id uuid,editorial_id uuid,estado_publicacion text,titulo text,poster_url text,banner_url text,vistas int default 0,likes_count int default 0);
    insert into public.contenido(id,autor_id,estado_publicacion,titulo) values('${video}','${owner}','aprobado','Tutorial'),('${draft}','${owner}','borrador','Secreto');
    create table public.network_businesses(id uuid primary key,owner_id uuid,nombre text,estado text,logo_url text,portada_url text);
    insert into public.network_businesses values('${business}','${owner}','Comercio','aprobado',null,null);
    create table public.gba_keynotes(id uuid primary key,slug text,title text,is_published boolean,published_by uuid);
    insert into public.gba_keynotes values('${keynote}','keynote','Keynote',true,'${owner}');
    create table public.notificaciones(id uuid primary key default gen_random_uuid(),usuario_id uuid,tipo text,titulo text,mensaje text,leida boolean default false,created_at timestamptz default now());
    create function public.vista_is_platform_admin() returns boolean language sql stable as $$select auth.uid()='${admin}'::uuid$$;
    create function public.vista_editorial_has_role(uuid,text) returns boolean language sql stable as $$select false$$;
    create function public.gba_workspace_has_role(text) returns boolean language sql stable as $$select false$$;`);
  const original=fs.readFileSync('supabase/migrations/202608150001_vista_credits_conversations_profiles.sql','utf8');
  const activity=fs.readFileSync('supabase/migrations/202608150004_vista_activity_feed.sql','utf8');
  await db.exec(original);
  await db.exec(activity.slice(0,activity.indexOf('create or replace function public.vista_can_manage_subject'))+'commit;');
  for(const name of ['vista_can_manage_subject','vista_subject_exists','vista_notify_mentions','vista_add_conversation','vista_delete_update','vista_toggle_update_like']) await db.exec(fn(activity,name));
  await db.exec(`insert into public.vista_updates(id,author_id,body) values('${update}','${owner}','Actualización');`);
  await db.exec(fs.readFileSync('supabase/migrations/20261003185415_vista_social_reliability.sql','utf8'));
  // Reapplication is safe, preserving IDs and permissions.
  await db.exec(fs.readFileSync('supabase/migrations/20261003185415_vista_social_reliability.sql','utf8'));
  await actor(owner);
  await save(creditPayload([credit,{role:'Guion',display_name:'Externo'}]));
  const pending=await inspect("select id from vista_credits where contributor_id=$1",[contributor]);
  const external=await inspect("select id from vista_credits where contributor_id is null");
  ok(await inspect('select count(*)::int from notificaciones'),1);
  await save(creditPayload([credit,{role:'Guion',display_name:'Externo'}]));
  ok(await inspect('select count(*)::int from notificaciones'),1);
  ok(await inspect('select id from vista_credits where contributor_id=$1',[contributor]),pending);
  ok(await inspect('select id from vista_credits where contributor_id is null'),external);
  await actor(stranger);
  await rejects(db.query('select vista_respond_credit($1,true)',[pending]),/no pertenece/);
  await rejects(db.query('select vista_respond_credit($1,false)',[external]),/no pertenece/);
  await rejects(save([]),/No puedes gestionar/);
  ok((await db.query('select * from vista_list_credits($1,$2)',['content',video])).rows.length,1);
  await actor(null); await rejects(db.query('select vista_respond_credit($1,true)',[external]),/sesión válida/);
  ok((await db.query('select * from vista_list_credits($1,$2)',['content',video])).rows.length,0);
  await actor(contributor); await db.query('select vista_respond_credit($1,true)',[pending]);
  await db.query('select vista_respond_credit($1,true)',[pending]);
  await rejects(db.query('select vista_respond_credit($1,false)',[pending]),/ya fue respondida/);
  ok(await inspect('select leida from notificaciones where usuario_id=$1',[contributor]),true);
  ok((await db.query('select * from vista_profile_credits($1)',[contributor])).rows[0].action_url,contentLink(video));
  await actor(owner);await save(creditPayload([credit]));
  ok(await inspect('select status from vista_credits where id=$1',[pending]),'accepted');
  ok(await inspect('select is_active from vista_credits where id=$1',[external]),false);
  await save(creditPayload([{...credit,role:'Edición'}]));
  const newInvite=await inspect("select id from vista_credits where status='pending' and is_active");
  ok(newInvite===pending,false);
  await actor(contributor);await rejects(db.query('select vista_respond_credit($1,true)',[pending]),/retirada/);
  await db.query('select vista_respond_credit($1,false)',[newInvite]);
  await actor(owner);await save(creditPayload([{...credit,role:'Edición',id:newInvite}]));
  ok(await inspect('select status from vista_credits where id=$1',[newInvite]),'declined');
  ok(await inspect('select count(*)::int from notificaciones'),2);
  await rejects(save([{role:'Edición',handle:'@creator',display_name:'Creator'},{role:'Edición',handle:'@creator',display_name:'Creator'}]),/No repitas/);
  ok(await inspect('select count(*)::int from vista_credits where is_active'),1);
  await rejects(save([{id:id(999),role:'Edición',display_name:'Falso'}]),/no pertenece/);
  await rejects(save([{role:'Editor',handle:'@hidden',display_name:'Hidden'}]),/GBA ID público/);
  await rejects(save([{role:'x',display_name:'Externo'}]),/necesita un rol/);
  await rejects(save(null),/deben ser una lista/);
  await actor(admin);ok(await scalar('select vista_can_manage_subject($1,$2)',['content',id(999)]),false);
  await actor(owner);await db.query('select vista_replace_credits($1,$2,$3)',['content',draft,[{role:'Autor',handle:'owner',display_name:'Owner'}]]);
  // A contributor may keep a hidden profile without losing their existing account association.
  await save(creditPayload([credit]));
  await db.exec('reset role');await db.query('update usuarios set perfil_publico=false where id=$1',[contributor]);await actor(owner);
  await save([{id:pending,role:'Tutorial',handle:'',display_name:'Creator',external:false}]);
  ok(await inspect('select contributor_id from vista_credits where id=$1',[pending]),contributor);
  await actor(stranger);
  ok((await db.query('select * from vista_profile_credits($1)',[contributor])).rows.length,0);
  ok((await db.query('select * from vista_list_credits($1,$2)',['content',draft])).rows.length,0);
  const comment=await scalar('select vista_add_conversation($1,$2,$3,null)',['content',video,'Hola']);
  const reply=await scalar('select vista_add_conversation($1,$2,$3,$4)',['content',video,'Respuesta',comment]);
  await actor(owner);await scalar('select vista_add_conversation($1,$2,$3,$4)',['content',video,'Gracias',reply]);
  ok(await inspect("select action_url from notificaciones where tipo='conversacion' and usuario_id=$1 order by created_at desc limit 1",[stranger]),contentLink(video));
  const secret=await scalar('select vista_add_conversation($1,$2,$3,null)',['content',video,'Secreto posterior']);
  await db.exec('reset role');await db.query("update contenido set estado_publicacion='borrador' where id=$1",[video]);await actor(stranger);
  ok((await db.query('select * from vista_list_conversation($1,$2)',['content',video])).rows.length,0);
  await actor(contributor);await rejects(db.query('select vista_delete_conversation($1)',[secret]),/cannot remove/);
  await actor(stranger);await db.query('select vista_delete_conversation($1)',[comment]);
  ok(await inspect('select status from vista_conversations where id=$1',[comment]),'deleted');
  ok(await inspect('select body from vista_conversations where id=$1',[comment]),'');
  ok(await inspect('select count(*)::int from vista_conversations where parent_id=$1',[comment]),1);
  await actor(null);await rejects(db.query('select vista_delete_conversation($1)',[reply]),/Authentication/);
  await db.exec('reset role'); await db.query("update contenido set estado_publicacion='aprobado' where id=$1",[video]);
  await actor(stranger);await scalar('select vista_add_conversation($1,$2,$3,null)',['content',video,'Mención @owner']);
  ok(await inspect("select action_url from notificaciones where tipo='conversacion' and usuario_id=$1 order by created_at desc limit 1",[owner]),contentLink(video));
  await db.exec('reset role');await db.query('update usuarios set perfil_publico=true where id=$1',[contributor]);await actor(stranger);
  await scalar('select vista_add_conversation($1,$2,$3,null)',['content',video,'Gracias @creator']);
  ok(await inspect("select action_url from notificaciones where tipo='mencion' and usuario_id=$1 order by created_at desc limit 1",[contributor]),contentLink(video));
  await scalar('select vista_add_conversation($1,$2,$3,$4)',['content',video,'Otra mención @creator',reply]);
  ok(await inspect("select action_url from notificaciones where tipo='mencion' and usuario_id=$1 order by created_at desc limit 1",[contributor]),contentLink(video));
  ok((await scalar('select vista_set_profile_follow($1,true)',[owner])).is_following,true);
  await scalar('select vista_set_profile_follow($1,true)',[owner]);
  ok(await inspect("select count(*)::int from notificaciones where tipo='nuevo_seguidor'"),1);
  ok((await scalar('select vista_set_profile_follow($1,false)',[owner])).followers,0);
  await rejects(db.query('select vista_set_profile_follow($1,true)',[stranger]),/cannot follow your own profile/);
  const liked=await scalar('select vista_toggle_update_like($1)',[update]);ok(liked.liked,true);ok(liked.likes_count,1);
  ok((await scalar('select vista_toggle_update_like($1)',[update])).likes_count,0);
  await actor(owner);
  await db.exec('reset role');await rejects(db.query("insert into vista_updates(author_id,body) values($1,'')",[owner]),/check constraint/);await actor(owner);
  await actor(owner);await db.query('select vista_delete_update($1)',[update]);
  ok(await inspect('select status from vista_updates where id=$1',[update]),'deleted');
  await rejects(db.query('select vista_add_conversation($1,$2,$3,null)',['update',update,'Hola']),/not found/);
  ok(await inspect("select (get_public_profile('owner')->>'colaboraciones')::int"),0);
  ok(await inspect("select has_function_privilege('anon','vista_respond_credit(uuid,boolean)','execute')"),false);
  ok(await inspect("select has_schema_privilege('authenticated','vista_social_private','usage')"),false);
  ok(await inspect("select count(*)::int from pg_class where relname in ('vista_credits','vista_conversations','vista_updates') and relrowsecurity"),3);
  console.log(`PASS: ${checks} social checks: consent, stable IDs, deduplication, ownership, private drafts, comments, deletion, notifications and links.`);
} catch(error) {console.error(error.message); if(error.position) console.error("SQL position:",error.position); process.exitCode=1;} finally {await db.close();}
