import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { PGlite } from '@electric-sql/pglite';
import { cleanAnswers, stepsFor, stepError, tally, safeCsvCell } from '../src/survey/questionnaire.js';

const db=new PGlite();let checks=0;
const ok=(a,b)=>{assert.deepEqual(a,b);checks++;};
const reject=async(p,match)=>{await assert.rejects(p,match);checks++;};
const scalar=async(sql,args=[])=>Object.values((await db.query(sql,args)).rows[0])[0];
const uid='00000000-0000-0000-0000-000000000001',adminId='00000000-0000-0000-0000-000000000002';
const actor=async(role,id='')=>{await db.exec('reset role');await db.query("select set_config('test.uid',$1,false)",[id]);await db.exec(`set role ${role}`);};
const base={roles:['player'],country:'MX',frequency:'weekly',content:['news','events'],server_info:['rules','map'],comment:'Queremos más periódicos.'};
const token=n=>`10000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const submit=(n,answers=base,version=1,trap='')=>scalar('select vista_submit_survey($1,$2,$3,$4)',[token(n),answers,version,trap]);
try {
  ok(stepsFor(base).includes('budget'),false);
  const adminAnswers={...base,roles:['admin','player'],placements:['free','hero'],goal:'visits',budget_status:'amount',budget_amount:150,currency:'MXN',payment:['card','transfer']};
  ok(stepsFor(adminAnswers).includes('budget'),true);
  ok(cleanAnswers({...adminAnswers,roles:['player']}).placements,undefined);
  ok(cleanAnswers({...adminAnswers,budget_status:'none'}).currency,undefined);
  ok(Boolean(stepError('budget',{budget_status:'amount',budget_amount:'',currency:'MXN'})),true);
  ok(stepError('budget',{budget_status:'amount',budget_amount:0,currency:'MXN'}),'');
  ok(tally([{answers:base},{answers:{...base,content:['news']}}],'content'),{total:2,values:[['news',2],['events',1]]});
  ok(safeCsvCell('=HYPERLINK("unsafe")'), '"\'=HYPERLINK(""unsafe"")"');
  await db.exec(`create role anon;create role authenticated;create schema auth;grant usage on schema auth to anon,authenticated;
    create table auth.users(id uuid primary key);insert into auth.users values('${uid}'),('${adminId}');
    create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
    create function public.vista_is_platform_admin() returns boolean language sql stable security definer set search_path=pg_catalog,pg_temp as $$select auth.uid()='${adminId}'::uuid$$;`);
  await db.exec(fs.readFileSync(path.resolve('supabase/migrations/20261003164023_vista_public_survey.sql'),'utf8'));
  await actor('anon');
  ok((await scalar("select to_jsonb(s) from vista_surveys s where key='vista-partners'")).is_open,true);
  await reject(db.query('select * from vista_survey_responses'),/permission denied/);
  await reject(db.query('select * from vista_survey_private.rate_windows'),/permission denied/);
  ok(await submit(1),{received:true,already_submitted:false});
  ok(await submit(1),{received:true,already_submitted:true});
  await reject(submit(2,base,2),/version changed/);
  await reject(submit(2,base,1,'robot'),/Invalid submission/);
  await reject(submit(2,{...base,roles:['root']}),/Unknown choice/);
  await reject(submit(2,{...base,content:['news','news']}),/Duplicate choices/);
  await reject(submit(2,{...base,content:['news','events','stories','tutorials']}),/number of choices/);
  await reject(submit(2,{...base,content:['other']}),/Specify other/);
  await reject(submit(2,{...base,comment:'x'.repeat(2001)}),/Invalid text/);
  await reject(submit(2,{...base,user_id:adminId}),/Unknown question/);
  await reject(submit(2,{...base,placements:['hero']}),/require administrator/);
  await reject(submit(2,{...adminAnswers,budget_amount:-1}),/budget amount/);
  await reject(submit(2,{...adminAnswers,currency:'OTHER',currency_other:'anything'}),/currency code/);
  ok((await submit(2,adminAnswers)).received,true);
  await actor('authenticated',uid);
  ok((await db.query('select * from vista_survey_responses')).rows.length,0);
  await db.query("update vista_surveys set is_open=false where key='vista-partners'");
  ok(await scalar("select is_open from vista_surveys where key='vista-partners'"),true);
  ok((await submit(3)).already_submitted,false);
  ok((await submit(4)).already_submitted,true);
  await actor('authenticated',adminId);
  ok((await db.query('select * from vista_survey_responses')).rows.length,3);
  await db.query("update vista_surveys set is_open=false where key='vista-partners'");
  await actor('anon');await reject(submit(5),/Survey closed/);
  await actor('authenticated',adminId);await db.query("update vista_surveys set is_open=true where key='vista-partners'");
  await actor('anon');
  await db.query("select set_config('request.headers',$1,false)",[JSON.stringify({'x-real-ip':'203.0.113.1'})]);
  for(let n=100;n<112;n++)ok((await submit(n)).received,true);
  await reject(submit(112),/Too many/);
  await db.exec('reset role');
  ok(await scalar("select count(*)::int from pg_class where relname in('vista_surveys','vista_survey_responses','rate_windows') and relrowsecurity"),3);
  ok(await scalar("select prosecdef from pg_proc where oid='public.vista_submit_survey(text,jsonb,integer,text)'::regprocedure"),false);
  ok(await scalar("select has_table_privilege('anon','vista_survey_responses','select')"),false);
  ok(await scalar("select has_table_privilege('anon','vista_survey_responses','insert')"),false);
  ok(await scalar("select has_function_privilege('anon','public.vista_submit_survey(text,jsonb,integer,text)','execute')"),true);
  console.log(`PASS: ${checks} checks for anonymous submission, private results, admin controls, validation, conditional questions, safe CSV, retry deduplication and rate limiting.`);
} catch(error) {console.error(error.message); if(error.position) console.error('SQL position:',error.position);process.exitCode=1;} finally {await db.close();}
