import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {UPDATE_TARGETS,REPOSITORY,buildUpdateManifest,verifyCandidate,newerThan} from '../scripts/workspace-update-manifest.mjs';
const commit='a'.repeat(40),version='0.1.2',bytes=Buffer.alloc(1000,7),sha256=createHash('sha256').update(bytes).digest('hex');
const artifacts=UPDATE_TARGETS.map(target=>{const [platform,architecture]=target.split('-');const file=platform==='darwin'?`workspace-${version}-${target}.app.tar.gz`:`gba-workspace-${version}-${target}.exe`;return {platform,architecture,file,version,url:`https://github.com/${REPOSITORY}/releases/download/workspace-v${version}-beta.1/${file}`,signature:Buffer.from('s'.repeat(200)).toString('base64'),sha256,size:bytes.length};});
const input={version,commit,notes:'Release notes',pubDate:'2026-10-10T05:00:00Z',artifacts,previous:{version:'0.1.1'}};
assert.equal(Object.keys(buildUpdateManifest(input).platforms).length,3);
assert.throws(()=>buildUpdateManifest({...input,previous:{version}}),/increase/);
assert.throws(()=>buildUpdateManifest({...input,artifacts:artifacts.slice(1)}),/three/);
assert.throws(()=>buildUpdateManifest({...input,artifacts:[...artifacts,artifacts[0]]}),/Duplicate/);
assert.throws(()=>buildUpdateManifest({...input,artifacts:artifacts.map(a=>({...a,url:a.url+'?secret=1'}))}),/permanent/);
assert.throws(()=>buildUpdateManifest({...input,artifacts:artifacts.map(a=>({...a,signature:''}))}),/signature/);
assert.throws(()=>buildUpdateManifest({...input,artifacts:artifacts.map(a=>({...a,url:a.url.replace('github.com','example.com')}))}),/permanent/);
assert.ok(newerThan('0.10.0','0.9.9'));assert.ok(!newerThan('0.1.1','0.1.2'));
const metadata={commit,updaters:[artifacts[0]],downloads:[{platform:'macos',architecture:'aarch64',version,sha256:'b'.repeat(64)}]};
const startup={commit,platform:'macos',sha256:'b'.repeat(64),installedAppTest:true,processStartup:true,installedExecutableMatches:true};
assert.equal(verifyCandidate(metadata,startup,bytes,{commit,version,target:'darwin-aarch64'}).file,artifacts[0].file);
assert.throws(()=>verifyCandidate(metadata,{...startup,commit:'c'.repeat(40)},bytes,{commit,version,target:'darwin-aarch64'}),/commits/);
assert.throws(()=>verifyCandidate(metadata,{...startup,installedAppTest:false},bytes,{commit,version,target:'darwin-aarch64'}),/acceptance/);
assert.throws(()=>verifyCandidate(metadata,startup,Buffer.alloc(1000,8),{commit,version,target:'darwin-aarch64'}),/bytes/);
console.log('PASS: increasing versions, complete native matrix, permanent URLs, signatures, installed acceptance and CI byte integrity.');
const minorArtifacts=artifacts.map(a=>({...a,version:'0.1.401',file:a.file.replaceAll('0.1.2','0.1.4.1'),url:a.url.replaceAll('0.1.2','0.1.4.1')}));
const minor={...input,version:'0.1.401',displayVersion:'0.1.4.1',mandatory:true,minimumNativeVersion:'0.1.401',artifacts:minorArtifacts,previous:{version:'0.1.4'}};
assert.equal(buildUpdateManifest(minor).displayVersion,'0.1.4.1');
assert.equal(buildUpdateManifest(minor).minimumNativeVersion,'0.1.401');
assert.throws(()=>buildUpdateManifest({...minor,minimumNativeVersion:'0.1.402'}),/exceeds/);
assert.throws(()=>buildUpdateManifest({...minor,displayVersion:'0.1.4.2'}),/differ/);
assert.throws(()=>buildUpdateManifest({...minor,minimumNativeVersion:'0.1.4'}),/Mandatory/);
console.log('PASS: public maintenance releases match native SemVer and mandatory minimums.');
