import assert from 'node:assert/strict';
import { build } from 'esbuild';
const bundle = await build({entryPoints:['src/workspace/workflowDemo.js'],bundle:true,platform:'node',format:'esm',write:false});
const { createWorkflowDemo, workflowDemoData, DEMO_ACTORS, demoPermissions, runWorkflowDemo } = await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString('base64')}`);
const state = createWorkflowDemo();
const artist = workflowDemoData(state, DEMO_ACTORS.artist, 'halloween-demo');
assert(artist.approvedDocuments.some(document => document.deliverable_id === 'accepted-research-demo'));
assert(!artist.tasks.some(task => task.id === 'research-task-demo'));
assert(!artist.versions.some(version => version.deliverable_id === 'research-task-demo'));
assert.equal(demoPermissions(DEMO_ACTORS.artist, 'halloween-demo', 'research-demo', state.tasks[0])['content.edit_assigned'], false);
assert.equal(demoPermissions(DEMO_ACTORS.lead, 'halloween-demo', 'art-demo', state.tasks[1])['task.assign'], false);
const modelBundle = await build({entryPoints:['src/workspace/documentModel.js'],bundle:true,platform:'node',format:'esm',write:false});
const { initialSection, reviewAction, canReviewTask } = await import(`data:text/javascript;base64,${Buffer.from(modelBundle.outputFiles[0].text).toString('base64')}`);
for (const [actorKey, expected] of [['researcher','work'], ['artist','work'], ['writer','work'], ['lead','reviews'], ['production','assignments'], ['coordinator','assignments'], ['productDirector','reviews'], ['quality','reviews'], ['direction','reviews'], ['viewer','documents']]) {
  const actor = DEMO_ACTORS[actorKey];
  assert.equal(initialSection(workflowDemoData(state, actor, 'halloween-demo'), 'halloween-demo', actor.id), expected, `${actor.name} starts in the right workspace`);
}
assert.equal(Boolean(demoPermissions(DEMO_ACTORS.production, 'halloween-demo', 'art-demo', state.tasks[1])['review.approve_art']), false);
assert.equal(demoPermissions(DEMO_ACTORS.coordinator, 'halloween-demo', 'research-demo', state.tasks[0])['unit.roles.grant'], undefined);
assert.equal(demoPermissions(DEMO_ACTORS.lead, 'halloween-demo', 'research-demo', state.tasks[0])['task.update_schedule'], false);
assert.equal(demoPermissions({ ...DEMO_ACTORS.productDirector, delegated: [] }, 'halloween-demo', 'research-demo', state.tasks[0])['task.assign'], false);
assert.equal(workflowDemoData(state, DEMO_ACTORS.platform, 'halloween-demo').tasks.length, 0);
assert.equal(workflowDemoData(state, DEMO_ACTORS.viewer, 'halloween-demo').projects.length, 1);
assert.equal(demoPermissions(DEMO_ACTORS.viewer, 'halloween-demo', 'art-demo', state.tasks[1])['content.create'], undefined);
const mutate = (current, actorKey, action, taskId, values = {}) => {
 const task = current.tasks.find(item => item.id === taskId);
 return runWorkflowDemo(current, DEMO_ACTORS[actorKey], action, { project_id: task.project_id, deliverable_id: task.id, ...values }, task.revision).state;
};
let flow = mutate(state, 'production', 'task.schedule', 'research-task-demo', { due_at: '2026-10-22T18:00:00Z', priority: 'high' });
assert(flow.events.some(event => event.deliverable_id === 'research-task-demo' && event.kind === 'deadline' && event.starts_at === '2026-10-22T18:00:00Z'));
flow = mutate(flow, 'researcher', 'comment.add', 'research-task-demo', { body: 'Necesito confirmar las fuentes.' });
assert(flow.comments.some(comment => comment.body === 'Necesito confirmar las fuentes.'));
flow = mutate(flow, 'researcher', 'task.transition', 'research-task-demo', { state: 'blocked', reason: 'Falta acceso a las fuentes.' });
assert.equal(flow.tasks.find(task => task.id === 'research-task-demo').state, 'blocked');
flow = mutate(flow, 'researcher', 'task.transition', 'research-task-demo', { state: 'in_progress' });
assert.equal(flow.tasks.find(task => task.id === 'research-task-demo').state, 'in_progress');
flow = mutate(flow, 'quality', 'qa.block', 'qa-task-demo', { reason: 'Los créditos y permisos no están completos.' });
let qa = flow.tasks.find(task => task.id === 'qa-task-demo');
const qaPerms = demoPermissions(DEMO_ACTORS.quality, 'halloween-demo', qa.area_id, qa);
assert(canReviewTask(qa, qaPerms, flow.areas.find(area => area.id === qa.area_id)));
assert.equal(reviewAction(qa, qaPerms, flow.areas.find(area => area.id === qa.area_id)), null);
assert.throws(() => mutate(flow, 'production', 'task.transition', 'qa-task-demo', { state: 'in_qa' }));
flow = mutate(flow, 'quality', 'qa.release', 'qa-task-demo', { reason: 'Se verificaron los créditos y permisos.' });
assert.equal(flow.tasks.find(task => task.id === 'qa-task-demo').state, 'in_progress');
assert.throws(() => mutate(flow, 'quality', 'task.transition', 'final-task-demo', { state: 'published' }));
flow = mutate(flow, 'direction', 'publication.approve', 'final-task-demo');
flow = mutate(flow, 'quality', 'task.transition', 'final-task-demo', { state: 'published' });
assert.equal(flow.tasks.find(task => task.id === 'final-task-demo').state, 'published');
flow = mutate(flow, 'direction', 'review.reopen', 'final-task-demo', { reason: 'Se necesita actualizar la pieza.' });
assert.equal(flow.tasks.find(task => task.id === 'final-task-demo').state, 'in_progress');
flow = mutate(flow, 'production', 'dependency.add', 'research-task-demo', { depends_on_id: 'cover-demo' });
assert.throws(() => mutate(flow, 'production', 'dependency.add', 'cover-demo', { depends_on_id: 'research-task-demo' }));
let round = mutate(state, 'direction', 'review.changes', 'cover-demo', { body: 'Corregir el contraste.' });
round.tasks.find(task => task.id === 'cover-demo').state = 'review';
assert.throws(() => mutate(round, 'direction', 'review.changes', 'cover-demo', { body: 'Otra corrección.' }));
round = mutate(round, 'direction', 'review.extra_round', 'cover-demo', { reason: 'Se agregó una referencia nueva.' });
round = mutate(round, 'direction', 'review.changes', 'cover-demo', { body: 'Aplicar la referencia nueva.' });
assert.equal(round.tasks.find(task => task.id === 'cover-demo').round, 2);
console.log('PASS: role entry points, scoped authority, scheduling, conversations, blockers, QA release, final approval, reopening, dependencies and correction rounds.');
