import assert from 'node:assert/strict';
import fs from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
import { pgcrypto } from '@electric-sql/pglite/contrib/pgcrypto';
const db = new PGlite({ extensions: { pgcrypto } });
let checks=0;
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const session=n=>`10000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const eq=(a,b)=>{assert.deepEqual(a,b);checks++;};
const denied=async(p,re=/permiso|permission|denied|autorizad|propio|Sesión|Membresía|ronda|QA|Dirección|cambió|Transición|cerrado/i)=>{await assert.rejects(p,re);checks++;};
async function actor(n){await db.exec('reset role');await db.query("select set_config('test.uid',$1,false),set_config('test.session',$2,false)",[n?id(n):'',n?session(n):'']);await db.exec('set role authenticated');}
async function scalar(q,args=[]){return Object.values((await db.query(q,args)).rows[0])[0];}
async function cmd(action,data,revision=null){return scalar('select public.workspace_command($1,$2,$3)',[action,data,revision]);}
async function admin(q,args=[]){await db.exec('reset role');return db.query(q,args);}
try {
await db.exec(`create role anon;create role authenticated;create role service_role;
 create schema auth;create schema extensions;create extension pgcrypto with schema extensions;
 create table auth.users(id uuid primary key,email text,encrypted_password text,updated_at timestamptz);
 create table auth.sessions(id uuid primary key,user_id uuid references auth.users(id));
 create schema vault;
 create table vault.secrets(id uuid primary key default gen_random_uuid(),secret text not null,name text,key_id uuid);
 create view vault.decrypted_secrets as select id,key_id,secret as decrypted_secret from vault.secrets;
 create function vault.create_secret(new_secret text,new_name text default null,new_description text default '',new_key_id uuid default null) returns uuid language sql as $$insert into vault.secrets(secret,name) values(new_secret,new_name) returning id$$;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create function auth.jwt() returns jsonb language sql stable as $$select jsonb_build_object('session_id',current_setting('test.session',true))$$;
 grant usage on schema auth to authenticated;
 grant execute on function auth.uid(),auth.jwt() to authenticated;
 create table public.usuarios(id uuid primary key references auth.users(id),rol text,nombre text,nombre_publico text,frase_seguridad text);
 alter table public.usuarios add column sello_editorial text;
 create table public.editoriales(id uuid primary key default gen_random_uuid(),nombre text,slug text,descripcion text,created_by uuid);
 create table public.solicitudes_editoriales(id uuid primary key,usuario_id uuid,nombre_noticiero text,descripcion text);
 create function public.vista_is_platform_admin() returns boolean language sql stable security definer as $$select exists(select 1 from public.usuarios where id=auth.uid() and rol in ('Dueño','Admin'))$$;
 create function public.vista_editorial_slugify(value text) returns text language sql immutable strict as $$select trim(both '-' from regexp_replace(lower(value),'[^a-z0-9]+','-','g'))$$;
 create table public.editorial_invitations(id uuid primary key,editorial_id uuid references public.editoriales(id),invited_user_id uuid references auth.users(id),role text,status text,expires_at timestamptz,invited_by uuid,responded_at timestamptz,updated_at timestamptz);
 create table public.editorial_members(editorial_id uuid,usuario_id uuid,role text,status text,invited_by uuid,updated_at timestamptz,unique(editorial_id,usuario_id));
 create table public.editorial_audit_log(editorial_id uuid,actor_id uuid,action text,target_type text,target_id text,details jsonb);
 create table public.gimg_recruitment_reviewers(user_id uuid,role text);
 create schema gimg_recruitment_private;grant usage on schema gimg_recruitment_private to authenticated;
 create function gimg_recruitment_private.active_session() returns boolean language sql stable security definer set search_path=pg_catalog,pg_temp as $$select auth.uid() is not null and exists(select 1 from auth.sessions where user_id=auth.uid() and id::text=auth.jwt()->>'session_id')$$;
 create table gimg_recruitment_private.identities(user_id uuid,recovery_hash text);
 create function public.gimg_recover_identity(text,text,text) returns boolean language sql as $$select false$$;
 create function gimg_recruitment_private.recover_identity(text,text,text) returns boolean language sql as $$select false$$;`);
for(let n=1;n<=12;n++) { await db.query("insert into auth.users values($1,$2,extensions.crypt('GBA-1234-SecureVault',extensions.gen_salt('bf',4)),now())",[id(n),`person${n}@gba.com`]);await db.query('insert into auth.sessions values($1,$2)',[session(n),id(n)]);await db.query('insert into public.usuarios values($1,$2,$3,$3,$4)',[id(n),n===1?'Dueño':'Usuario',`person${n}`,n===12?'sol':'old secret']); }
await db.query("insert into public.gimg_recruitment_reviewers values($1,'director')",[id(2)]);
for(const file of ['202608010001_gba_workspace_phase1.sql','202608140001_public_keynotes.sql','20261010005048_workspace_gimg.sql','20261010005053_workspace_licenses.sql','20261010005130_gba_id_secure_gateway.sql','20261010005309_gimg_role_isolation.sql','20261009123356_gimg_identity_role_isolation.sql','20261010010427_workspace_scope_search_path.sql']) await db.exec(fs.readFileSync(new URL(`../supabase/migrations/${file}`,import.meta.url),'utf8'));
const restoredCheckpoint=await scalar('select extensions.pgp_sym_decrypt(b.encrypted_payload,k.decrypted_secret)::jsonb from workspace_private.identity_rollout_backups b join vault.decrypted_secrets k on k.id=b.key_id');
eq(restoredCheckpoint.length,12);eq(restoredCheckpoint[0].frase_seguridad,'old secret');
eq(restoredCheckpoint[0].encrypted_password,await scalar('select pin_hash from workspace_private.id_secrets where user_id=$1',[id(1)]));
await actor(1);await denied(db.query('select * from workspace_private.identity_rollout_backups'));await admin('select 1');
await actor(1);eq(await scalar("select public.workspace_license_recipient(' @PERSON5 ')"),id(5));await denied(scalar("select public.workspace_license_recipient('missingperson')"),/GBA ID único/i);
await actor(2);await denied(scalar("select public.workspace_license_recipient('person5')"));await admin('select 1');
const unit=await scalar("select id from public.workspace_units where slug='gimg'");
await actor(1);const keynoteCollection=await scalar("select id from public.gba_workspace_collections where slug='keynotes'");const oldKeynote=(await db.query("insert into public.gba_workspace_documents(collection_id,title,content_markdown,status,owner_id,created_by,updated_by) values($1,'Keynote conservada','Contenido aprobado de Keynote','approved',$2,$2,$2) returning id",[keynoteCollection,id(1)])).rows[0].id;const keynote=await scalar('select to_jsonb(public.gba_workspace_publish_keynote($1,$2,$3))',[oldKeynote,'Esta Keynote conserva su publicación y su contenido.', '2026-10-08']);eq(keynote.content_markdown,'Contenido aprobado de Keynote');eq(keynote.is_published,true);
await actor(1);eq((await scalar('select public.workspace_context()')).platform_owner,true);eq((await scalar('select public.workspace_context()')).units.length,0);await denied(cmd('project.create',{unit_id:unit,title:'Not editorial'}));
await actor(1);eq(await scalar('select gimg_recruitment_private.director()'),false);eq(await scalar('select gimg_recruitment_private.reviewer()'),false);await actor(2);eq(await scalar('select gimg_recruitment_private.director()'),true);
await db.exec('reset role');await denied(db.query('update public.usuarios set rol=$1 where id=$2',['gimg_direction',id(2)]),/rangos generales/);const otherUnit=(await db.query("insert into public.workspace_units(slug,name) values('gba-other','Otra unidad') returning id")).rows[0].id;await denied(db.query("insert into public.workspace_access_grants(user_id,access_role,unit_id,scope_type,scope_id,reason) values($1,'gimg_direction',$2,'unit',$2,'Prueba de aislamiento')",[id(2),otherUnit]),/unidad GIMG/);eq((await db.query('select rol from public.usuarios where id=$1',[id(2)])).rows[0].rol,'Usuario');await denied(db.query("insert into public.workspace_access_grants(user_id,access_role,unit_id,scope_type,scope_id,reason) values($1,'gba_platform_owner',$2,'unit',$2,'Prueba de aislamiento')",[id(2),unit]),/workspace_role_domain/);
for(const [n,rank] of [[9,'Admin'],[10,'Editor'],[11,'Forge Engineer'],[12,'ANIMA Researcher']]){await admin('update public.usuarios set rol=$1 where id=$2',[rank,id(n)]);await actor(n);eq(await scalar('select gimg_recruitment_private.director()'),false);eq(await scalar('select gimg_recruitment_private.reviewer()'),false);eq((await scalar('select public.workspace_context()')).units.length,0);await denied(cmd('project.create',{unit_id:unit,title:'Rango general no es cargo GIMG'}));}
await admin("insert into public.editoriales(id,nombre,slug) values($1,'GIMG','gimg'),($2,'Editorial externa','external')",[id(80),id(81)]);await db.query("insert into public.editorial_invitations(id,editorial_id,invited_user_id,role,status,expires_at) values($1,$2,$3,'editor','pending',now()+interval '1 day'),($4,$5,$6,'editor','pending',now()+interval '1 day')",[id(82),id(80),id(5),id(83),id(81),id(4)]);await actor(5);eq(await scalar('select public.vista_editorial_respond_invitation($1,true)',[id(82)]),true);await admin('select 1');eq((await db.query('select rol from public.usuarios where id=$1',[id(5)])).rows[0].rol,'Usuario');await actor(4);eq(await scalar('select public.vista_editorial_respond_invitation($1,true)',[id(83)]),true);await admin('select 1');eq((await db.query('select rol from public.usuarios where id=$1',[id(4)])).rows[0].rol,'Editor');
// Live schema has many NULL ranks: GIMG enrollment must preserve them too.
await admin('update public.usuarios set rol=null where id=$1',[id(7)]);
await db.query("insert into public.solicitudes_editoriales values($1,$2,'Global Insight Media Group','GIMG'),($3,$4,'Editorial nueva externa','Externa')",[id(84),id(7),id(85),id(8)]);
await actor(7);await denied(scalar('select to_jsonb(public.vista_approve_editorial_request($1))',[id(84)]),/Platform admin/);
await actor(1);const newGimg=await scalar('select to_jsonb(public.vista_approve_editorial_request($1))',[id(84)]);eq(newGimg.slug,'global-insight-media-group');
await admin('select 1');eq((await db.query('select rol from public.usuarios where id=$1',[id(7)])).rows[0].rol,null);eq((await db.query('select role from public.editorial_members where editorial_id=$1 and usuario_id=$2',[newGimg.id,id(7)])).rows[0].role,'owner');eq(await scalar('select count(*)::integer from public.solicitudes_editoriales where id=$1',[id(84)]),0);
await actor(1);await scalar('select to_jsonb(public.vista_approve_editorial_request($1))',[id(85)]);await admin('select 1');eq((await db.query('select rol from public.usuarios where id=$1',[id(8)])).rows[0].rol,'Editor');
await actor(2);const project=await cmd('project.create',{unit_id:unit,title:'Halloween',brief:'Edición'});const second=await cmd('project.create',{unit_id:unit,title:'Leyendas'});
const areas=await db.query('select * from public.workspace_areas where project_id=$1',[project.id]);const art=areas.rows.find(x=>x.specialty==='art');
for(const [n,role] of [[3,'gimg_production_lead'],[4,'gimg_area_lead'],[5,'gimg_contributor'],[6,'gimg_quality_manager'],[7,'gimg_project_director'],[8,'gimg_viewer']]){
 await cmd('member.save',{unit_id:unit,user_id:id(n),membership_status:'active'});
 await cmd('grant.save',{unit_id:unit,user_id:id(n),access_role:role,scope_type:n===4?'area':n===7?'project':'unit',scope_id:n===4?art.id:n===7?project.id:unit,expires_at:n===7?new Date(Date.now()+86400000).toISOString():null,reason:'Asignación explícita aprobada'});
 if([4,6,7].includes(n))await cmd('assignment.save',{unit_id:unit,user_id:id(n),assignment_role:n===4?'area_lead':n===6?'qa':'direction',project_id:project.id,area_id:n===4?art.id:null});
}
await actor(2);await cmd('member.save',{unit_id:unit,user_id:id(9),membership_status:'active'});await cmd('grant.save',{unit_id:unit,user_id:id(9),access_role:'gimg_contributor',scope_type:'unit',scope_id:unit,reason:'Cargo de GIMG independiente del rango general'});await actor(9);await denied(cmd('project.create',{unit_id:unit,title:'Admin global con cargo colaborador'}));await admin('select 1');eq((await db.query('select rol from public.usuarios where id=$1',[id(9)])).rows[0].rol,'Admin');await actor(2);await denied(cmd('grant.save',{unit_id:unit,user_id:id(9),access_role:'Admin',scope_type:'unit',scope_id:unit,reason:'Rango general inválido para GIMG'}),/check constraint/);
await actor(3);let task=await cmd('task.create',{project_id:project.id,area_id:art.id,title:'Portada',responsible_id:id(5)});
await denied(db.query('update public.workspace_deliverables set final_approved_by=$1 where id=$2',[id(3),task.id]));
await actor(5);eq((await db.query('select id from public.workspace_projects')).rows.map(x=>x.id),[project.id]);eq((await db.query('select id from public.workspace_deliverables')).rows.length,1);await denied(cmd('project.create',{unit_id:unit,title:'Denied'}));
task=await cmd('task.transition',{project_id:project.id,deliverable_id:task.id,state:'in_progress'},task.revision);
task=await cmd('version.submit',{project_id:project.id,deliverable_id:task.id,content_markdown:'Primera entrega',asset_url:'https://controlled.example/private/cover',change_summary:'Versión inicial'},task.revision);
await actor(3);await denied(cmd('version.submit',{project_id:project.id,deliverable_id:task.id,content_markdown:'Producción no asignada'},task.revision));await denied(cmd('task.transition',{project_id:project.id,deliverable_id:task.id,state:'area_approved'},task.revision));await denied(cmd('publication.approve',{project_id:project.id,deliverable_id:task.id},task.revision));
await actor(4);task=await cmd('review.changes',{project_id:project.id,deliverable_id:task.id,body:'Ajusta los créditos'},task.revision);
await actor(5);task=await cmd('version.submit',{project_id:project.id,deliverable_id:task.id,content_markdown:'Entrega corregida',credits:'Autora: person5',change_summary:'Créditos corregidos'},task.revision);
await actor(4);await denied(cmd('review.changes',{project_id:project.id,deliverable_id:task.id,body:'Otra ronda'},task.revision),/ronda/);task=await cmd('task.transition',{project_id:project.id,deliverable_id:task.id,state:'area_approved'},task.revision);await denied(cmd('publication.approve',{project_id:project.id,deliverable_id:task.id},task.revision));
await actor(3);task=await cmd('task.schedule',{project_id:project.id,deliverable_id:task.id,due_at:'2026-11-01T18:00:00Z',priority:'high'},task.revision);eq((await db.query('select starts_at from public.workspace_events where deliverable_id=$1',[task.id])).rows.length,1);task=await cmd('task.transition',{project_id:project.id,deliverable_id:task.id,state:'in_qa'},task.revision);
await actor(6);task=await cmd('task.transition',{project_id:project.id,deliverable_id:task.id,state:'qa_approved'},task.revision);await denied(cmd('task.transition',{project_id:project.id,deliverable_id:task.id,state:'published'},task.revision),/Dirección/);
await actor(2);task=await cmd('publication.approve',{project_id:project.id,deliverable_id:task.id},task.revision);await actor(6);task=await cmd('task.transition',{project_id:project.id,deliverable_id:task.id,state:'published'},task.revision);eq(task.state,'published');
await actor(null);await db.exec('set role anon');const publicRows=(await db.query('select * from public.workspace_publications')).rows;eq(publicRows.length,1);eq(publicRows[0].content_markdown,'Entrega corregida');eq(publicRows[0].source_url,undefined);
await actor(6);task=await cmd('qa.block',{project_id:project.id,deliverable_id:task.id,reason:'Crédito faltante detectado después de publicar'},task.revision);await actor(null);await db.exec('set role anon');eq((await db.query('select * from public.workspace_publications')).rows.length,0);await actor(3);await denied(cmd('task.transition',{project_id:project.id,deliverable_id:task.id,state:'published'},task.revision),/QA/);await actor(6);task=await cmd('qa.release',{project_id:project.id,deliverable_id:task.id,reason:'Crédito corregido y verificado por QA'},task.revision);eq(task.final_approved_by,null);

eq((await db.query('select * from public.workspace_versions where deliverable_id=$1',[task.id])).rows.length,2);await denied(db.query("update public.workspace_versions set content_markdown='forged' where deliverable_id=$1",[task.id]));
await actor(2);await cmd('member.save',{unit_id:unit,user_id:id(5),membership_status:'suspended'});await actor(5);eq((await db.query('select * from public.workspace_versions')).rows.length,0);await denied(cmd('comment.add',{project_id:project.id,deliverable_id:task.id,body:'Bypass'},task.revision));
await actor(2);await cmd('member.save',{unit_id:unit,user_id:id(5),membership_status:'active'});
await cmd('delegation.save',{unit_id:unit,user_id:id(8),scope_type:'deliverable',scope_id:task.id,permission_keys:['task.read','content.comment'],starts_at:new Date(Date.now()-10000).toISOString(),expires_at:new Date(Date.now()+60000).toISOString(),reason:'Consulta de la portada aprobada'});
await actor(8);eq((await db.query('select * from public.workspace_deliverables')).rows.length,1);eq((await db.query('select * from public.workspace_versions')).rows.length,0);const hiddenVersion=(await admin('select id from public.workspace_versions where deliverable_id=$1 and version_number=1',[task.id])).rows[0].id;await actor(8);await denied(scalar('select public.workspace_asset_link($1)',[hiddenVersion]));
await actor(5);const version=(await db.query('select id from public.workspace_versions where deliverable_id=$1 and version_number=1',[task.id])).rows[0].id;eq((await scalar('select public.workspace_asset_link($1)',[version])).url,'https://controlled.example/private/cover');await denied(db.query('select * from workspace_private.asset_links'),/permission|denied/);
await admin("update public.workspace_assignments set expires_at=now()-interval '1 second',starts_at=now()-interval '1 day' where user_id=$1",[id(5)]);await actor(5);eq((await db.query('select * from public.workspace_deliverables')).rows.length,0);await admin('update public.workspace_assignments set expires_at=null where user_id=$1',[id(5)]);await actor(8);

await admin('update public.workspace_delegations set expires_at=now()-interval \'1 second\',starts_at=now()-interval \'1 day\' where delegate_user_id=$1',[id(8)]);await actor(8);eq((await db.query('select * from public.workspace_deliverables')).rows.length,0);
// Own deliverables cannot be approved by their author even with Direction.
await actor(2);let own=await cmd('task.create',{project_id:project.id,area_id:art.id,title:'Own',responsible_id:id(2)});own=await cmd('version.submit',{project_id:project.id,deliverable_id:own.id,content_markdown:'Owned'},own.revision);own=await cmd('task.transition',{project_id:project.id,deliverable_id:own.id,state:'area_approved'},own.revision);own=await cmd('task.transition',{project_id:project.id,deliverable_id:own.id,state:'in_qa'},own.revision);own=await cmd('task.transition',{project_id:project.id,deliverable_id:own.id,state:'qa_approved'},own.revision);await denied(cmd('publication.approve',{project_id:project.id,deliverable_id:own.id},own.revision),/propio/);
await actor(3);await denied(scalar('select public.workspace_export_audit($1)',[unit]));await actor(2);eq((await scalar('select public.workspace_export_audit($1)',[unit])).records.some(r=>r.action==='audit.exported'),true);
await actor(1);const issued=await scalar('select public.workspace_issue_license($1,$2,$3)',[7200,'Pilot',id(5)]);eq(issued.code.length,48);eq((await scalar('select public.workspace_license_codes()'))[0].code_hash,undefined);
await actor(6);eq(Boolean((await scalar('select public.workspace_activate_license($1)',[issued.code])).error),true);
await actor(5);let license=await scalar('select public.workspace_activate_license($1)',[issued.code]);eq(license.user_id,id(5));eq(new Date(license.expires_at).getTime()-new Date(license.starts_at).getTime(),7200000);eq((await scalar('select public.workspace_license_status()')).active,true);eq((await scalar('select public.workspace_activate_license($1)',[issued.code])).id,license.id);
await admin("update public.workspace_licenses set starts_at=now()-interval '2 hours',expires_at=now()-interval '1 hour' where id=$1",[license.id]);await actor(5);eq((await scalar('select public.workspace_license_status()')).active,false);
await actor(1);await scalar('select public.workspace_revoke_license($1,$2)',[issued.id,'Revocación de prueba']);await actor(5);eq((await scalar('select public.workspace_license_status()')).active,false);eq((await db.query('select * from public.workspace_deliverables')).rows.length,1);
await actor(1);await denied(scalar("select public.gba_id_gateway('login','person5','1234','','origin','device',null)"),/permission|denied/i);
await db.exec('reset role');let login=await scalar("select public.gba_id_gateway('login','person5','1234','','origin','device',null)");eq(login.user_id,id(5));eq(await scalar("select count(*)::integer from public.usuarios where frase_seguridad is not null"),0);eq(await scalar("select encrypted_password=extensions.crypt('GBA-1234-SecureVault',encrypted_password) from auth.users where id=$1",[id(5)]),false);
await db.query("insert into gimg_recruitment_private.identities values($1,encode(sha256(convert_to($2,'UTF8')),'hex'))",[id(6),'a'.repeat(48)]);eq((await scalar("select public.gba_id_gateway('recover','person6','9876',$1,'origin','device',null)",['a'.repeat(48)])).user_id,id(6));
for(let n=0;n<5;n++)eq(Boolean((await scalar("select public.gba_id_gateway('login','person7','0000','','origin','device',null)")).error),true);eq(Boolean((await scalar("select public.gba_id_gateway('login','person7','1234','','origin','device',null)")).retry_after),true);
const reset=await scalar("select public.gba_id_gateway('recover','person5','5678','old secret','origin','device',null)");eq(reset.user_id,id(5));await actor(5);eq((await scalar('select public.workspace_context()')).units.length,0);eq((await db.query('select * from public.workspace_deliverables')).rows.length,0);
await db.exec('reset role');
const shortPhraseRecovery=await scalar("select public.gba_id_gateway('recover','person12','9999',' Sol ','origin','device',null)");eq(shortPhraseRecovery.user_id,id(12));
eq((await scalar("select public.gba_id_gateway('login','person12','9999','','origin','device',null)")).user_id,id(12));
eq(Boolean((await scalar("select public.gba_id_gateway('prepare','newperson','1234','sol','origin','device',null)")).error),true);
console.log(`PASS: ${checks} Workspace assertions: direct API denial, scopes, full editorial cycle, suspension, delegation expiry, immutable versions, self approval, licenses, recovery and session revocation.`);
}catch(error){console.error(error.message,error.where||'',error.params||'');process.exitCode=1;}finally{await db.close();}
