-- Rollback-only live acceptance for 1.5.5. No real user's edition is changed.
create temporary table workspace_notifications_test_result(checks integer,credentials_preserved boolean,keynotes_preserved boolean);
do $$
declare
 ids uuid[]:=array[gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid()];
 sessions uuid[]:=array[gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid()];
 u uuid;p jsonb;t jsonb;r jsonb;notice jsonb;inbox jsonb;removed jsonb;a uuid;n integer;checks integer:=0;denied boolean;
 password_snapshot text;keynote_snapshot text;rich jsonb:='{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Rollback-only concept"}]}]}'::jsonb;
begin
 select md5(coalesce(string_agg(id::text||coalesce(encrypted_password,''),'' order by id),'')) into password_snapshot from auth.users;
 select md5(coalesce(string_agg(to_jsonb(k)::text,'' order by id),'')) into keynote_snapshot from public.gba_keynotes k;
 for n in 1..6 loop
 insert into auth.users(id,email,aud,role,raw_user_meta_data,is_sso_user,is_anonymous,created_at,updated_at) values(ids[n],'workspace-inbox-test-'||ids[n]||'@example.invalid','authenticated','authenticated','{}',false,false,now(),now());
 insert into auth.sessions(id,user_id,created_at,updated_at) values(sessions[n],ids[n],now(),now());
 end loop;
 select id into u from public.workspace_units where slug='gimg';
 insert into public.workspace_unit_memberships(unit_id,user_id,membership_status) select u,x,'active' from unnest(ids) x;
 insert into public.workspace_access_grants(user_id,unit_id,access_role,scope_type,scope_id,reason) values(ids[1],u,'gimg_direction','unit',u,'Rollback-only inbox acceptance'),(ids[2],u,'gimg_production_lead','unit',u,'Rollback-only inbox acceptance'),(ids[3],u,'gimg_contributor','unit',u,'Rollback-only inbox acceptance'),(ids[4],u,'gimg_quality_manager','unit',u,'Rollback-only inbox acceptance');
 insert into public.workspace_access_grants(user_id,access_role,scope_type,reason) values(ids[6],'gba_platform_owner','platform','Rollback-only technical role');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[1],'session_id',sessions[1],'role','authenticated')::text,true);perform set_config('role','authenticated',true);
 p:=public.workspace_command('project.create',jsonb_build_object('unit_id',u,'title','Rollback-only inbox edition','brief','Preserved original concept'));
 select id into a from public.workspace_areas where project_id=(p->>'id')::uuid and specialty='art';
 perform set_config('role','postgres',true);
 insert into public.workspace_access_grants(user_id,unit_id,access_role,scope_type,scope_id,reason) values(ids[5],u,'gimg_area_lead','area',a,'Rollback-only area lead');
 insert into public.workspace_assignments(user_id,assignment_role,unit_id,project_id,area_id,assigned_by) values(ids[5],'area_lead',u,(p->>'id')::uuid,a,ids[1]);
 perform set_config('role','authenticated',true);
 r:=public.workspace_import_concept((p->>'id')::uuid,jsonb_build_object('title','Editable concept','content_document',rich));
 if jsonb_array_length(public.workspace_reference_history((r->>'id')::uuid))<>2 then raise exception 'Concept history missing';end if;checks:=checks+1;
 if (public.workspace_reference_history((r->>'id')::uuid)->1->'snapshot'->>'content_markdown')<>'Preserved original concept' then raise exception 'Original concept changed';end if;checks:=checks+1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[2],'session_id',sessions[2],'role','authenticated')::text,true);
 denied:=false;begin perform public.workspace_remove_edition((p->>'id')::uuid,1,p->>'title','Production without archive delegation');exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Production removed edition';end if;checks:=checks+1;
 t:=public.workspace_command('task.create',jsonb_build_object('project_id',p->>'id','area_id',a,'title','Private assignment','responsible_id',ids[3]));
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[3],'session_id',sessions[3],'role','authenticated')::text,true);
 inbox:=public.workspace_notifications();select x into notice from jsonb_array_elements(inbox->'items') x where x->>'deliverable_id'=t->>'id';
 if notice is null or notice->>'event_type'<>'assignment.updated' then raise exception 'Assigned contributor not notified';end if;checks:=checks+1;
 perform public.workspace_read_notification((notice->>'id')::uuid);
 if not exists(select 1 from jsonb_array_elements(public.workspace_notifications()->'items') x where x->>'id'=notice->>'id' and x->>'read_at' is not null) then raise exception 'Own read did not persist';end if;checks:=checks+1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[4],'session_id',sessions[4],'role','authenticated')::text,true);
 denied:=false;begin perform public.workspace_read_notification((notice->>'id')::uuid);exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Read another inbox';end if;checks:=checks+1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[6],'session_id',sessions[6],'role','authenticated')::text,true);
 if jsonb_array_length(public.workspace_notifications()->'items')<>0 then raise exception 'GBA role inherited GIMG inbox';end if;checks:=checks+1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[2],'session_id',sessions[2],'role','authenticated')::text,true);
 t:=public.workspace_command('task.schedule',jsonb_build_object('project_id',p->>'id','deliverable_id',t->>'id','due_at',now()+interval '1 hour','priority','high'),(t->>'revision')::integer);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[3],'session_id',sessions[3],'role','authenticated')::text,true);
 perform public.workspace_notifications();perform public.workspace_notifications();
 if (select count(*) from jsonb_array_elements(public.workspace_notifications()->'items') x where x->>'event_type'='deadline' and x->>'deliverable_id'=t->>'id')<>1 then raise exception 'Deadline duplicate or missing';end if;checks:=checks+1;
 t:=public.workspace_command('version.submit',jsonb_build_object('project_id',p->>'id','deliverable_id',t->>'id','content_markdown','Disposable review content'),(t->>'revision')::integer);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[5],'session_id',sessions[5],'role','authenticated')::text,true);
 if not exists(select 1 from jsonb_array_elements(public.workspace_notifications()->'items') x where x->>'event_type'='review.requested' and x->>'deliverable_id'=t->>'id') then raise exception 'Area lead did not receive review';end if;checks:=checks+1;
 perform set_config('role','postgres',true);update public.workspace_unit_memberships set membership_status='suspended' where unit_id=u and user_id=ids[3];perform set_config('role','authenticated',true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[3],'session_id',sessions[3],'role','authenticated')::text,true);
 if jsonb_array_length(public.workspace_notifications()->'items')<>0 then raise exception 'Suspended inbox visible';end if;checks:=checks+1;
 perform set_config('role','postgres',true);update public.workspace_unit_memberships set membership_status='active' where unit_id=u and user_id=ids[3];perform set_config('role','authenticated',true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[1],'session_id',sessions[1],'role','authenticated')::text,true);
 denied:=false;begin perform public.workspace_remove_edition((p->>'id')::uuid,1,'Wrong name','Disposable removal reason');exception when others then denied:=true;end;if not denied then raise exception 'Wrong confirmation accepted';end if;checks:=checks+1;
 denied:=false;begin perform public.workspace_remove_edition((p->>'id')::uuid,0,p->>'title','Disposable removal reason');exception when serialization_failure then denied:=true;end;if not denied then raise exception 'Stale revision removed';end if;checks:=checks+1;
 removed:=public.workspace_remove_edition((p->>'id')::uuid,1,p->>'title','Rollback-only removal verification');
 if exists(select 1 from public.workspace_projects where id=(p->>'id')::uuid) then raise exception 'Removed edition still visible';end if;checks:=checks+1;
 denied:=false;begin perform public.workspace_command('project.save',jsonb_build_object('project_id',p->>'id','title','Bypass','status','active'),(removed->>'revision')::integer);exception when others then denied:=true;end;if not denied then raise exception 'Generic save restored removed edition';end if;checks:=checks+1;
 if not exists(select 1 from jsonb_array_elements(public.workspace_removed_editions(u)) x where x->>'id'=p->>'id') then raise exception 'Direction cannot restore';end if;checks:=checks+1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[3],'session_id',sessions[3],'role','authenticated')::text,true);
 if exists(select 1 from jsonb_array_elements(public.workspace_notifications()->'items') x where x->>'project_id'=p->>'id') then raise exception 'Removed edition inbox visible';end if;checks:=checks+1;
 denied:=false;begin perform public.workspace_restore_edition((p->>'id')::uuid,(removed->>'revision')::integer);exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Contributor restored edition';end if;checks:=checks+1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[1],'session_id',sessions[1],'role','authenticated')::text,true);
 perform public.workspace_restore_edition((p->>'id')::uuid,(removed->>'revision')::integer);
 if (select status from public.workspace_projects where id=(p->>'id')::uuid)<>'active' or jsonb_array_length(public.workspace_reference_history((r->>'id')::uuid))<>2 then raise exception 'Restoration lost state or history';end if;checks:=checks+1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ids[1],'session_id',gen_random_uuid(),'role','authenticated')::text,true);
 denied:=false;begin perform public.workspace_notifications();exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Revoked session read inbox';end if;checks:=checks+1;
 perform set_config('role','postgres',true);
 insert into workspace_notifications_test_result values(checks,password_snapshot=(select md5(coalesce(string_agg(id::text||coalesce(encrypted_password,''),'' order by id),'')) from auth.users where id<>all(ids)),keynote_snapshot=(select md5(coalesce(string_agg(to_jsonb(k)::text,'' order by id),'')) from public.gba_keynotes k));
end;$$;
