import React, { useRef, useState } from 'react';
import WorkEditor from './WorkEditor';
import { CommandForm, TaskList, choices } from './ui';
import { STATES, dateLabel } from './gimgModel';
import WorkConversation from './WorkConversation';
import WorkOperations from './WorkOperations';
import { taskIsMine, canReviewTask, nextStep, hasReviewPermission } from './documentModel';

export function CreateWork({ project, data, actorId, personal, command, busy, onCreated }) {
  const [open, setOpen] = useState(false);
  const createTrigger = useRef(null);
  const areas = data.areas.filter(area => area.project_id === project.id && data.areaPermissions?.[area.id]?.['task.create'] && (personal || data.areaPermissions?.[area.id]?.['task.assign']));
  if (!areas.length) return null;
  return <details open={open} onToggle={event => setOpen(event.currentTarget.open)} className="gw-create-work"><summary ref={createTrigger}>{personal ? 'Crear documento' : 'Nueva asignación'}</summary><CommandForm resetOnSuccess initial={{ area_id: areas.length === 1 ? areas[0].id : '' }} busy={busy} button={personal ? 'Crear y empezar a escribir' : 'Asignar trabajo'} fields={{ title: personal ? 'Título del documento' : 'Título de la asignación', ...(personal ? {} : { description: { label: 'Qué debe realizar y entregar esta persona', type: 'textarea' } }), area_id: { label: 'Área', options: choices(areas, 'name') }, ...(personal ? {} : { responsible_id: { label: 'Asignar a', options: choices(data.members, 'display_name'), optional: true } }) }} onSave={async values => { const task = await command('task.create', { ...values, responsible_id: personal ? actorId : values.responsible_id }); if (task) { onCreated(task); setOpen(false); createTrigger.current?.focus(); } return task; }} /></details>;
}

export function PersonalWork({ project, data, task, actorId, command, api, busy, onPick, previewMode, onDirtyChange, onReference }) {
  const [filter, setFilter] = useState(() => task && ['area_approved','in_qa','qa_approved','published','archived'].includes(task.state) ? 'all' : 'active');
  const order = { changes_requested: 0, blocked: 1, in_progress: 2, assigned: 3, pending: 3, review: 4 };
  const mine = data.tasks.filter(item => item.project_id === project.id && taskIsMine(item, actorId)).sort((a,b) => (order[a.state] ?? 5) - (order[b.state] ?? 5) || (a.due_at ? new Date(a.due_at).getTime() : Infinity) - (b.due_at ? new Date(b.due_at).getTime() : Infinity));
  const tasks = mine.filter(item => filter === 'all' || !['area_approved', 'in_qa', 'qa_approved', 'published', 'archived'].includes(item.state));
  const selected = tasks.find(item => item.id === task?.id) || tasks[0];
  return <section className="gw-personal-work"><div className="gw-work-heading"><div><h1>Mi trabajo</h1><p>Tus asignaciones y los documentos que estás preparando.</p></div><CreateWork project={project} data={data} actorId={actorId} personal command={command} busy={busy} onCreated={onPick} /></div>
    <div className="gw-personal-layout"><aside className="gw-personal-list"><label><span className="gw-sr-only">Mostrar mi trabajo</span><select value={filter} onChange={event => setFilter(event.target.value)}><option value="active">Trabajo pendiente</option><option value="all">Todo mi trabajo</option></select></label><TaskList tasks={tasks} selectedId={selected?.id} onPick={onPick} /></aside>
      {selected ? <WorkEditor key={selected.id} task={selected} data={data} actorId={actorId} api={api} command={command} previewMode={previewMode} busy={busy} onDirtyChange={onDirtyChange} onReference={onReference} /> : <div className="gw-work-empty"><h3>No tienes trabajo pendiente en esta edición.</h3><p>Cuando el responsable de tu área te asigne trabajo, podrás abrirlo aquí, preparar el documento y enviarlo a revisión.</p><button type="button" onClick={onReference}>Consultar documentos de la edición</button></div>}
    </div>
  </section>;
}

export function AreaAssignments({ project, data, task, command, busy, onPick, onReview }) {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('open');
  const [areaId, setAreaId] = useState('');
  const scoped = data.tasks.filter(item => item.project_id === project.id && data.taskPermissions?.[item.id]?.['task.assign']);
  const areas = data.areas.filter(area => area.project_id === project.id && data.areaPermissions?.[area.id]?.['task.assign']);
  const matches = item => filter === 'all' || (filter === 'blocked' ? item.state === 'blocked' : filter === 'unassigned' ? !item.responsible_id : filter === 'late' ? item.due_at && new Date(item.due_at) < new Date() && !['published','archived'].includes(item.state) : !['published','archived'].includes(item.state));
  const tasks = scoped.filter(item => matches(item) && (!areaId || item.area_id === areaId) && `${item.title} ${data.members.find(member => member.user_id === item.responsible_id)?.display_name || ''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const selected = tasks.find(item => item.id === task?.id) || tasks[0];
  const permissions = selected && data.taskPermissions[selected.id];
  return <section className="gw-work-section"><div className="gw-work-heading"><div><h1>Asignaciones</h1><p>Organiza el trabajo de {areas.length === 1 ? areas[0].name : 'la edición'}: quién lo realiza, qué entrega y cuándo.</p></div><CreateWork project={project} data={data} command={command} busy={busy} onCreated={onPick} /></div>
    <div className="gw-work-filters"><label><span className="gw-sr-only">Buscar asignación o persona</span><input type="search" placeholder="Buscar trabajo o persona" value={query} onChange={event => setQuery(event.target.value)} /></label><label><span className="gw-sr-only">Filtrar asignaciones</span><select value={filter} onChange={event => setFilter(event.target.value)}><option value="open">Trabajo abierto ({scoped.filter(item => !['published','archived'].includes(item.state)).length})</option><option value="unassigned">Sin responsable ({scoped.filter(item => !item.responsible_id).length})</option><option value="blocked">Bloqueado ({scoped.filter(item => item.state === 'blocked').length})</option><option value="late">Con retraso</option><option value="all">Todo el trabajo</option></select></label>{areas.length > 1 && <label><span className="gw-sr-only">Filtrar por área</span><select value={areaId} onChange={event => setAreaId(event.target.value)}><option value="">Todas las áreas</option>{areas.map(area => <option key={area.id} value={area.id}>{area.name}</option>)}</select></label>}<span>{tasks.length} {tasks.length === 1 ? 'trabajo' : 'trabajos'}</span></div>
    <div className="gw-assignment-layout"><div className="gw-list">{tasks.map(item => <button type="button" key={item.id} className={selected?.id === item.id ? 'gw-selected' : ''} onClick={() => onPick(item)}><strong>{item.title}</strong><p>{data.members.find(member => member.user_id === item.responsible_id)?.display_name || 'Sin responsable'}</p><small>{STATES[item.state]} · {dateLabel(item.due_at)}</small></button>)}{!tasks.length && <p className="gw-empty">Todavía no hay asignaciones en tu área.</p>}</div>
      {selected && <section className="gw-assignment-detail"><h3>{selected.title}</h3><p>{STATES[selected.state]} · {data.areas.find(area => area.id === selected.area_id)?.name}</p><p className="gw-next-step">{nextStep(selected)}</p>{canReviewTask(selected, permissions, data.areas.find(area => area.id === selected.area_id)) && <button type="button" onClick={() => onReview(selected)}>Atender entrega en Revisión</button>}{['pending', 'assigned', 'in_progress', 'review', 'changes_requested', 'blocked'].includes(selected.state) ? <CommandForm key={selected.id + selected.revision} initial={selected} busy={busy} fields={{ title: 'Asignación', description: { label: 'Indicaciones para la persona', type: 'textarea' }, responsible_id: { label: 'Responsable', options: choices(data.members, 'display_name'), optional: true } }} button="Guardar asignación" onSave={values => command('task.save', { ...values, deliverable_id: selected.id, collaborator_ids: selected.collaborator_ids || [] }, selected.revision)} /> : <p>La versión está aceptada. Su contenido y asignación se conservan.</p>}
        {permissions['task.update_schedule'] && <details className="gw-disclosure"><summary>Fecha de entrega y prioridad</summary><CommandForm key={`schedule-${selected.id}-${selected.revision}`} initial={selected} busy={busy} button="Guardar fecha" fields={{ due_at: { label: 'Fecha de entrega', type: 'datetime-local', optional: true }, priority: { label: 'Prioridad', options: { low: 'Baja', normal: 'Normal', high: 'Alta', urgent: 'Urgente' } } }} onSave={values => command('task.schedule', { ...values, deliverable_id: selected.id }, selected.revision)} /></details>}
        <details className="gw-disclosure"><summary>Trabajo que debe completarse primero</summary><p>Una dependencia evita iniciar o publicar este encargo antes de que el trabajo indicado esté publicado o archivado.</p>{(data.dependencies || []).filter(item => item.deliverable_id === selected.id).map(item => <p key={item.depends_on_id}>{data.tasks.find(task => task.id === item.depends_on_id)?.title || 'Trabajo relacionado'}</p>)}<CommandForm key={`dependency-${selected.id}`} busy={busy} button="Añadir dependencia" fields={{ depends_on_id: { label: 'Trabajo previo', options: choices(scoped.filter(item => item.id !== selected.id)) } }} onSave={values => command('dependency.add', { ...values, deliverable_id: selected.id }, selected.revision)} /></details>
        <WorkOperations task={selected} permissions={permissions} command={command} busy={busy} />
        <WorkConversation task={selected} data={data} command={command} busy={busy} />
      </section>}
    </div>
  </section>;
}

export function EditionCalendar({ actorId, project, data, permissions, command, busy, onPick }) {
  const events = data.events.filter(event => event.project_id === project.id).sort((a, b) => new Date(a.starts_at) - new Date(b.starts_at));
  return <section className="gw-work-section"><h2>Calendario de la edición</h2><p>Entregas, revisiones y fechas editoriales de {project.title}.</p>
    {permissions['task.update_schedule'] && <details className="gw-disclosure"><summary>Añadir fecha</summary><CommandForm busy={busy} button="Añadir hito" fields={{ title: 'Título', kind: { label: 'Tipo', options: { milestone: 'Hito', review: 'Revisión', editorial: 'Fecha editorial' } }, starts_at: { label: 'Inicio', type: 'datetime-local' }, ends_at: { label: 'Fin', type: 'datetime-local', optional: true } }} onSave={values => command('event.save', values)} /></details>}
    {!events.length && <p className="gw-empty">Todavía no hay fechas registradas para esta edición.</p>}
    <div className="gw-list">{events.map(event => <article key={event.id}><h3>{event.title}</h3><p>{dateLabel(event.starts_at)}{event.ends_at && ` → ${dateLabel(event.ends_at)}`} · {{ milestone: 'Hito', review: 'Revisión', editorial: 'Fecha editorial', deadline: 'Entrega' }[event.kind] || event.kind}</p>{event.deliverable_id && data.tasks.some(task => task.id === event.deliverable_id && (taskIsMine(task, actorId) || data.taskPermissions?.[task.id]?.['task.assign'] || hasReviewPermission(data.taskPermissions?.[task.id] || {}) || data.approvedDocuments?.some(document => document.deliverable_id === task.id))) && <button type="button" onClick={() => onPick(data.tasks.find(task => task.id === event.deliverable_id))}>Abrir trabajo</button>}{permissions['task.update_schedule'] && event.kind !== 'deadline' && <details className="gw-disclosure"><summary>Modificar fecha</summary><CommandForm key={`${event.id}-${event.revision}`} initial={event} busy={busy} fields={{ title: 'Título', starts_at: { label: 'Inicio', type: 'datetime-local' }, ends_at: { label: 'Fin', type: 'datetime-local', optional: true } }} button="Guardar fecha" onSave={values => command('event.save', { ...values, id: event.id, kind: event.kind }, event.revision)} /></details>}</article>)}</div>
  </section>;
}
