import React, { useState } from 'react';
import { AlertTriangle, Trash2, RotateCcw } from 'lucide-react';
import { dateLabel } from './gimgModel';
export default function EditionRemoval({ project, removed, canRemove, onRemove, onRestore, busy }) {
  const [confirming,setConfirming]=useState(false),[confirmation,setConfirmation]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState('');
  async function remove(event){event.preventDefault();setError('');try{await onRemove(project,confirmation,reason);setConfirming(false);setConfirmation('');setReason('');}catch(failure){setError(failure.message);}}
  async function restore(item){setError('');try{await onRestore(item);}catch(failure){setError(failure.message);}}
  return <section className="gw-edition-removal"><h3>Ediciones eliminadas</h3><p>Retira una edición del espacio activo cuando ya no deba aparecer para el equipo. Puedes restaurarla después.</p>
    {project && canRemove && <>{!confirming ? <button type="button" disabled={busy} onClick={()=>setConfirming(true)}><Trash2 size={15}/>Eliminar «{project.title}»</button> : <form onSubmit={remove} className="gw-removal-confirmation"><div className="gw-removal-warning"><AlertTriangle size={21}/><div><strong>Esta edición desaparecerá para el equipo.</strong><p>Ya no podrán abrirla ni continuar sus tareas. Se conservarán documentos, originales e historial; seguirán contando en el límite de almacenamiento. Las publicaciones existentes en VISTA no se retirarán.</p></div></div><label>Escribe el nombre exacto: {project.title}<input value={confirmation} onChange={event=>setConfirmation(event.target.value)} autoComplete="off" required disabled={busy}/></label><label>Motivo de la eliminación<textarea value={reason} onChange={event=>setReason(event.target.value)} minLength={10} maxLength={2000} required disabled={busy}/></label><div className="gw-form-actions"><button type="submit" className="gw-danger" disabled={busy || confirmation!==project.title || reason.trim().length<10}>Confirmar eliminación</button><button type="button" disabled={busy} onClick={()=>setConfirming(false)}>Cancelar</button></div></form>}</>}
    {error && <p role="alert" className="gw-error">{error}</p>}
    <div className="gw-list">{removed.map(item=><article key={item.id}><h4>{item.title}</h4><p>Eliminada {dateLabel(item.deleted_at)}</p><p>{item.deletion_reason}</p><button type="button" disabled={busy} onClick={()=>void restore(item)}><RotateCcw size={15}/>Restaurar edición</button></article>)}{!removed.length && <p>No hay ediciones eliminadas dentro de tu alcance.</p>}</div>
  </section>;
}
