import React, { useEffect, useState } from 'react';
import { CommandForm, choices, rpc } from './ui';
import { STATES, PRIORITIES, dateLabel } from './gimgModel';
export default function TaskDetail({task:t,data,command,busy,previewMode,onDirtyChange}){
 const [permissions,setPermissions]=useState({}),[content,setContent]=useState(''),[asset,setAsset]=useState(''),[credits,setCredits]=useState(''),[change,setChange]=useState(''),[error,setError]=useState('');
 const versions=data.versions.filter(v=>v.deliverable_id===t.id).sort((a,b)=>b.version_number-a.version_number),comments=data.comments.filter(c=>c.deliverable_id===t.id),area=data.areas.find(a=>a.id===t.area_id);
 useEffect(()=>{let live=true;if(previewMode){setPermissions(new Proxy({}, {get:()=>true}));return;}rpc('workspace_permissions',{p_unit:t.unit_id,p_project:t.project_id,p_area:t.area_id,p_deliverable:t.id}).then(p=>{if(live)setPermissions(p);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[t.id,t.revision,previewMode]);
 useEffect(()=>{setContent(versions[0]?.content_markdown||'');setCredits(versions[0]?.credits||'');setAsset('');setChange('');},[t.id,t.current_version]);
 const dirty=Boolean(content!==(versions[0]?.content_markdown||'')||credits!==(versions[0]?.credits||'')||asset||change);
 useEffect(()=>{onDirtyChange?.(dirty);},[dirty,onDirtyChange]);
 useEffect(()=>()=>onDirtyChange?.(false),[onDirtyChange]);
 useEffect(()=>{if(!dirty)return;const warn=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const run=(a,d={})=>command(a,{project_id:t.project_id,deliverable_id:t.id,...d},t.revision);
 const reasonAction=async(a)=>{const reason=window.prompt('Motivo o verificación (mínimo 10 caracteres)');if(reason)await run(a,{reason});};
 const transitions=[...(t.state==='assigned'?[['in_progress','task.update_status']]:[]),...(t.state==='review'?[['area_approved',`review.approve_${area?.specialty}`]]:[]),...(t.state==='area_approved'?[['in_qa','review.queue_qa']]:[]),...(t.state==='in_qa'?[['qa_approved','qa.approve']]:[]),...(t.state==='qa_approved'&&t.final_approved_by?[['published','publication.execute']]:[]),...(t.state==='published'?[['archived','asset.archive']]:[])];
 return <section className="gw-panel"><div className="gw-row"><h2>{t.title}</h2><span className="gw-badge">{STATES[t.state]}</span></div><p>{t.description}</p>{t.state==='published'&&<a href='/?gimg-publications=1' target='_blank' rel='noopener noreferrer'>Ver publicación en VISTA</a>}<p>{area?.name} · {PRIORITIES[t.priority]} · {dateLabel(t.due_at)}</p><p>Versión {t.current_version} · Ronda {t.round} · {t.extra_rounds} rondas adicionales autorizadas</p>{t.block_reason&&<p className="gw-alert" role="alert">{t.block_reason}</p>}{error&&<p role="alert">{error}</p>}
 <div className="gw-actions">{transitions.filter(([,key])=>permissions[key]).map(([state])=><button key={state} disabled={busy} onClick={()=>void run('task.transition',{state})}>{STATES[state]}</button>)}{t.state==='qa_approved'&&!t.final_approved_by&&permissions['publication.approve_final']&&<button disabled={busy} onClick={()=>void run('publication.approve')}>Aprobar publicación final</button>}{permissions['review.authorize_extra_round']&&<button disabled={busy} onClick={()=>void reasonAction('review.extra_round')}>Autorizar otra ronda</button>}{['area_approved','in_qa','qa_approved','published','archived'].includes(t.state)&&permissions['review.reopen']&&<button disabled={busy} onClick={()=>void reasonAction('review.reopen')}>Reabrir</button>}{permissions['qa.block_release']&&!t.qa_blocked&&<button disabled={busy} onClick={()=>void reasonAction('qa.block')}>Bloquear salida por QA</button>}{t.qa_blocked&&permissions['qa.approve']&&<button disabled={busy} onClick={()=>void reasonAction('qa.release')}>Verificar corrección y liberar QA</button>}{permissions['task.block']&&t.state!=='blocked'&&<button disabled={busy} onClick={()=>{const reason=window.prompt('Motivo del bloqueo');if(reason)void run('task.transition',{state:'blocked',reason});}}>Registrar bloqueo</button>}{t.state==='blocked'&&!t.qa_blocked&&permissions['task.block']&&<button disabled={busy} onClick={()=>void run('task.transition',{state:t.blocked_from})}>Retirar bloqueo</button>}</div>
 {permissions['task.assign']&&<CommandForm key={'assign'+t.revision} busy={busy} initial={t} fields={{title:'Título',description:{label:'Descripción',type:'textarea',optional:true},responsible_id:{label:'Responsable',options:choices(data.members,'display_name')}}} button="Actualizar asignación" onSave={d=>run('task.save',{...d,collaborator_ids:t.collaborator_ids||[]})}/>}
 {permissions['task.update_schedule']&&<CommandForm key={'schedule'+t.revision} busy={busy} initial={t} fields={{due_at:{label:'Fecha de entrega',type:'datetime-local',optional:true},priority:{label:'Prioridad',options:PRIORITIES}}} button="Guardar fecha y prioridad" onSave={d=>run('task.schedule',d)}/>}
 {permissions['task.assign']&&<CommandForm busy={busy} fields={{depends_on_id:{label:'Debe completarse primero',options:choices(data.tasks.filter(x=>x.project_id===t.project_id&&x.id!==t.id))}}} button="Añadir dependencia" onSave={d=>run('dependency.add',d)}/>}
 {permissions['content.edit_assigned']&&['pending','assigned','in_progress','review','changes_requested'].includes(t.state)&&<form onSubmit={e=>{e.preventDefault();void run('version.submit',{content_markdown:content,asset_url:asset||null,credits,change_summary:change});}}><h3>Nueva versión</h3><label>Documento Markdown<textarea className="gw-editor" value={content} onChange={e=>setContent(e.target.value)}/></label><label>Enlace al activo en repositorio controlado<input type="url" placeholder="https://…" value={asset} onChange={e=>setAsset(e.target.value)}/></label><label>Créditos y permisos<textarea value={credits} onChange={e=>setCredits(e.target.value)}/></label><label>Resumen de cambios<input required value={change} onChange={e=>setChange(e.target.value)}/></label><div className="gw-actions"><button className="gw-primary" disabled={busy}>Entregar versión para revisión</button></div></form>}
 {['review','in_qa'].includes(t.state)&&permissions['review.request_changes']&&<CommandForm busy={busy} fields={{body:{label:'Solicitud consolidada de cambios',type:'textarea'}}} button="Solicitar cambios" onSave={d=>run('review.changes',d)}/>}
 {permissions['qa.raise_issue']&&<CommandForm busy={busy} fields={{body:{label:'Incidencia de QA',type:'textarea'}}} button='Registrar incidencia' onSave={d=>run('qa.issue',d)}/>}
 {permissions['content.comment']&&<CommandForm busy={busy} fields={{body:{label:'Comentario',type:'textarea'}}} button="Comentar" onSave={d=>run('comment.add',d)}/>}
 <h3>Comentarios y verificaciones</h3>{comments.map(c=><article className="gw-history" key={c.id}><strong>{c.kind==='qa_issue'?'Incidencia de QA':c.kind==='changes'?'Cambios solicitados':c.kind==='verified'?'Cambios verificados':'Comentario'}</strong><p>{c.body}</p><small>{dateLabel(c.created_at)} · Ronda {c.round}</small></article>)}<h3>Versiones conservadas</h3>{versions.map(v=><details className="gw-history" key={v.id}><summary>Versión {v.version_number} · {v.change_summary}</summary><p>{dateLabel(v.created_at)}</p><pre>{v.content_markdown}</pre><p>{v.credits}</p>{permissions['asset.download_source']&&<button disabled={busy} onClick={async()=>{try{const result=await rpc('workspace_asset_link',{p_version_id:v.id});window.open(result.url,'_blank','noopener,noreferrer');}catch(e){setError(e.message);}}}>Abrir activo en repositorio</button>}</details>)}
 </section>;
}
