import React, { useState } from 'react';
import { CommandForm, choices } from './ui';
import { GIMG_ROLES as ROLES, MEMBERSHIP, dateLabel } from './gimgModel';
export default function TeamPanel({data,permissions,command,busy,unitId,projectId}){
 const [scope,setScope]=useState('project');const scopeChoices=scope==='unit'?{[unitId]:'Toda la unidad'}:scope==='project'?choices(data.projects):scope==='area'?choices(data.areas.filter(a=>a.project_id===projectId),'name'):choices(data.tasks.filter(t=>t.project_id===projectId));
 return <section><h2>Equipo, funciones y vigencia</h2><div className="gw-table"><table><thead><tr><th>Integrante</th><th>Membresía</th><th>Vigencia</th><th>Cargos y proyectos</th></tr></thead><tbody>{data.members.map(m=><tr key={m.user_id}><td><strong>{m.display_name}</strong><br/><small>@{m.handle}</small></td><td>{MEMBERSHIP[m.membership_status]}</td><td>{dateLabel(m.expires_at)}</td><td>{data.assignments.filter(a=>a.user_id===m.user_id).map(a=><div key={a.id}>{a.assignment_role} · {data.projects.find(p=>p.id===a.project_id)?.title||'Unidad'} · {dateLabel(a.expires_at)}</div>)}</td></tr>)}</tbody></table></div>
 {permissions['unit.members.invite']&&<CommandForm busy={busy} fields={{handle:'GBA ID existente',membership_status:{label:'Estado inicial',options:{accepted:'Aceptado',active:'Activo',continuity_requested:'Continuidad solicitada',continuity_confirmed:'Continuidad confirmada'}},expires_at:{label:'Vigencia del acceso',type:'datetime-local',optional:true}}} button="Incorporar o actualizar miembro" onSave={d=>command('member.save',d)}/>}
 {permissions['unit.members.suspend']&&<CommandForm busy={busy} fields={{user_id:{label:'Integrante',options:choices(data.members,'display_name')},membership_status:{label:'Estado',options:{suspended:'Suspendido',inactive:'Inactivo',departed:'Baja'}},reason:'Motivo'}} button="Revocar acceso operativo" onSave={d=>command('member.save',d)}/>}
 {permissions['unit.roles.grant']&&<><h3 className="gw-section">Rol técnico y alcance</h3><label>Alcance<select value={scope} onChange={e=>setScope(e.target.value)}><option value="unit">Unidad</option><option value="project">Proyecto</option><option value="area">Área</option><option value="deliverable">Entregable</option></select></label><CommandForm key={scope+projectId} busy={busy} fields={{user_id:{label:'Integrante',options:choices(data.members,'display_name')},access_role:{label:'Rol técnico',options:ROLES},scope_id:{label:'Objeto del alcance',options:scopeChoices},expires_at:{label:'Vencimiento',type:'datetime-local',optional:true},reason:'Motivo de asignación'}} button="Asignar rol técnico" onSave={d=>command('grant.save',{...d,scope_type:scope})}/><h3>Función organizacional</h3><CommandForm busy={busy} fields={{user_id:{label:'Integrante',options:choices(data.members,'display_name')},assignment_role:{label:'Función',options:{direction:'Dirección',production:'Producción',area_lead:'Responsable de área',research:'Investigación',writing:'Redacción',design:'Maquetación',illustration:'Ilustración',photography:'Fotografía',qa:'QA'}},area_id:{label:'Área',options:choices(data.areas.filter(a=>a.project_id===projectId),'name'),optional:true},expires_at:{label:'Vigencia',type:'datetime-local',optional:true}}} button="Asignar función en el proyecto" onSave={d=>command('assignment.save',d)}/><h3>Delegación escrita y temporal</h3><CommandForm key={'delegate'+scope+projectId} busy={busy} fields={{user_id:{label:'Delegado',options:choices(data.members,'display_name')},scope_id:{label:'Alcance',options:scopeChoices},permission_keys:'Permisos separados por coma',starts_at:{label:'Inicio',type:'datetime-local'},expires_at:{label:'Vencimiento',type:'datetime-local'},reason:{label:'Mandato escrito',type:'textarea'}}} button="Registrar delegación" onSave={d=>command('delegation.save',{...d,scope_type:scope,permission_keys:d.permission_keys.split(',').map(k=>k.trim()).filter(Boolean)})}/><div className="gw-list">{data.grants.filter(g=>!g.revoked_at).map(g=><article key={g.id}><strong>{ROLES[g.access_role]}</strong><p>{data.members.find(m=>m.user_id===g.user_id)?.display_name} · {g.scope_type} · {dateLabel(g.expires_at)}</p><button disabled={busy} onClick={()=>void command('grant.revoke',{id:g.id})}>Revocar rol</button></article>)}{data.delegations.filter(d=>!d.revoked_at).map(d=><article key={d.id}><strong>Delegación · {dateLabel(d.expires_at)}</strong><p>{d.reason}</p><p>{d.permission_keys.join(', ')}</p><button disabled={busy} onClick={()=>void command('delegation.revoke',{id:d.id})}>Revocar delegación</button></article>)}</div></>}
 </section>;
}
