import React, { useEffect, useRef, useState } from 'react';
import { supabase } from '../supabaseClient';
import { useAuth } from '../context/AuthContext';
import KeynotesWorkspace from '../workspace/KeynotesWorkspace';
import LicensePanel from '../workspace/LicensePanel';
import TaskDetail from '../workspace/TaskDetail';
import TeamPanel from '../workspace/TeamPanel';
import { CommandForm, TaskList, Activity, rpc, choices } from '../workspace/ui';
import { dateLabel, summary, GIMG_ROLES as ROLES } from '../workspace/gimgModel';
import '../workspace/workspace.css';

const tabs={home:'Mi jornada',projects:'Proyectos',tasks:'Entregables',calendar:'Calendario',team:'Equipo',audit:'Actividad',keynotes:'Keynotes',licenses:'Licencias'};
const demo={projects:[{id:'halloween-demo',unit_id:'gimg-demo',title:'Edición Halloween',brief:'Historias y arte para la edición de octubre.',status:'active',revision:1}],areas:[{id:'art-demo',project_id:'halloween-demo',name:'Ilustración',specialty:'art'}],tasks:[{id:'cover-demo',project_id:'halloween-demo',unit_id:'gimg-demo',area_id:'art-demo',title:'Portada de Halloween',description:'Preparar la portada y verificar créditos.',responsible_id:'demo-user',collaborator_ids:[],priority:'high',state:'review',due_at:'2026-10-30T18:00:00Z',current_version:1,revision:1,round:0}],members:[{user_id:'demo-user',display_name:'Integrante de demostración',membership_status:'active'}],versions:[{id:'version-demo',deliverable_id:'cover-demo',version_number:1,content_markdown:'## Propuesta de portada\n\nPrimera versión para revisión.',change_summary:'Propuesta inicial',credits:'Ilustración del equipo',created_at:'2026-10-08T18:00:00Z'}],comments:[],events:[],audit:[],assignments:[],grants:[],delegations:[]};
const empty={projects:[],areas:[],tasks:[],members:[],events:[],audit:[],versions:[],comments:[],assignments:[],grants:[],delegations:[]};
export default function Workspace({previewMode=false}) {
 const {user}=useAuth();const [tab,setTab]=useState('home'),[context,setContext]=useState(null),[unitId,setUnitId]=useState(''),[projectId,setProjectId]=useState(''),[selectedId,setSelectedId]=useState(''),[data,setData]=useState(empty),[permissions,setPermissions]=useState({}),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[lastVisit]=useState(()=>Number(localStorage.getItem('gba-workspace-last-visit')||0));const generation=useRef(0);
 const userId=previewMode?'demo-user':user?.id, project=data.projects.find(p=>p.id===projectId),task=data.tasks.find(t=>t.id===selectedId),totals=summary(data.tasks,userId);
 async function load(){const seq=++generation.current;setLoading(true);try{
  if(previewMode){setContext({units:[{id:'gimg-demo',name:'GIMG'}],platform_owner:true});setUnitId('gimg-demo');setProjectId(demo.projects[0].id);setData(demo);setSelectedId('cover-demo');setPermissions(new Proxy({}, {get:()=>true}));return;}
  const ctx=await rpc('workspace_context');if(seq!==generation.current)return;setContext(ctx);const u=ctx.units.find(x=>x.id===unitId)?.id||ctx.units[0]?.id||'';setUnitId(u);if(!u){setData(empty);return;}
  const tables={projects:'workspace_projects',areas:'workspace_areas',tasks:'workspace_deliverables',events:'workspace_events',audit:'workspace_audit',assignments:'workspace_assignments',grants:'workspace_access_grants',delegations:'workspace_delegations'};
  const results=await Promise.all(Object.entries(tables).map(async([key,table])=>{let q=supabase.from(table).select('*').eq('unit_id',u);if(key==='audit')q=q.order('created_at',{ascending:false}).limit(200);const {data,error}=await q;if(error)throw error;return [key,data||[]];}));
  const next=Object.fromEntries(results),p=next.projects.find(x=>x.id===projectId)?.id||next.projects[0]?.id||'';const contextualTask=next.tasks.find(t=>t.id===selectedId&&t.project_id===p)||next.tasks.find(t=>t.project_id===p);
  const contextualArea=contextualTask?.area_id||next.areas.find(a=>a.project_id===p)?.id||null;
  const [unitPerm,projectPerm,directoryPerm]=await Promise.all([rpc('workspace_permissions',{p_unit:u}),rpc('workspace_permissions',{p_unit:u,p_project:p||null}),rpc('workspace_permissions',{p_unit:u,p_project:p||null,p_area:contextualArea,p_deliverable:contextualTask?.id||null})]);
  const perm={...projectPerm};for(const [key,value] of Object.entries(unitPerm))if(key.startsWith('unit.')||key==='project.create')perm[key]=value;
  next.members=directoryPerm['unit.members.read']?await rpc('workspace_directory',{p_unit:u,p_project:p||null,p_area:contextualArea,p_deliverable:contextualTask?.id||null}):[];
  const ids=next.tasks.map(t=>t.id);for(const [key,table] of [['versions','workspace_versions'],['comments','workspace_comments']]){if(!ids.length){next[key]=[];continue;}const {data,error}=await supabase.from(table).select('*').in('deliverable_id',ids).order('created_at',{ascending:false});if(error)throw error;next[key]=data||[];}
  if(seq!==generation.current)return;setData(next);setProjectId(p);setPermissions(perm);setSelectedId(current=>next.tasks.some(t=>t.id===current)?current:next.tasks.find(t=>t.project_id===p)?.id||'');localStorage.setItem('gba-workspace-last-visit',String(Date.now()));
 }catch(e){if(seq===generation.current)setNotice(e.message||'No pudimos abrir Workspace. Vuelve a intentarlo.');}finally{if(seq===generation.current)setLoading(false);}}
 useEffect(()=>{void load();return()=>{generation.current++;};},[userId,unitId,projectId,previewMode]);
 async function command(action,payload,revision=null){if(previewMode){setNotice('Demostración local. Las acciones requieren una sesión real.');return null;}setBusy(true);setNotice('');try{const result=await rpc('workspace_command',{p_action:action,p_data:{unit_id:unitId,project_id:projectId,...payload},p_revision:revision});await load();setNotice('Cambio guardado en Workspace.');return result;}catch(e){setNotice(e.message);return null;}finally{setBusy(false);}}
 const pick=t=>{setProjectId(t.project_id);setSelectedId(t.id);setTab('tasks');};const disabled=busy||previewMode;const role=context?.grants?.find(g=>g.unit_id===unitId)?.access_role;
 return <div className="gw"><header><div><p className="gw-eyebrow">WORKSPACE</p><h1>El trabajo toma forma aquí.</h1><p>{previewMode?'Demostración local de GIMG':context?.units?.find(u=>u.id===unitId)?.name||'Espacio de GBA'}</p></div><div><strong>{user?.nombre_publico||user?.nombre||'GBA ID'}</strong><p>{ROLES[role]||'Acceso según asignación'}</p><button onClick={()=>void load()} disabled={loading}>Actualizar</button></div></header><main>
 <nav aria-label="Workspace">{Object.entries(tabs).filter(([id])=>(id!=='licenses'||context?.platform_owner)&&(id!=='keynotes'||previewMode||context?.keynotes_access)).map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {previewMode&&<p className="gw-alert">Vista de demostración local. No modifica cuentas, permisos ni datos reales.</p>}{notice&&<p className="gw-alert" role="alert">{notice}</p>}{loading&&<p role="status">Cargando Workspace…</p>}
 {tab==='keynotes'?<KeynotesWorkspace previewMode={previewMode}/>:tab==='licenses'?<LicensePanel previewMode={previewMode}/>:!context?.units?.length&&!loading?<div className="gw-empty"><h2>Tu equipo está por comenzar.</h2><p>Dirección debe incorporar tu GBA ID y asignarte permisos para una unidad. Una licencia de escritorio no concede acceso editorial.</p></div>:<>
 <div className="gw-row"><label>Unidad<select value={unitId} onChange={e=>setUnitId(e.target.value)}>{context?.units?.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Proyecto<select value={projectId} onChange={e=>{setProjectId(e.target.value);setSelectedId('');}}><option value="">Selecciona un proyecto</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label></div>
 {tab==='home'&&<><div className="gw-cards">{[['Mi trabajo',totals.mine.length],['Por revisar',totals.reviews.length],['Fuera de fecha',totals.late.length],['Bloqueados',totals.blocked.length]].map(([label,count])=><article key={label}><p>{label}</p><strong>{count}</strong></article>)}</div><h2>Tu próxima entrega</h2><TaskList tasks={[...totals.mine].sort((a,b)=>new Date(a.due_at||'9999')-new Date(b.due_at||'9999'))} onPick={pick}/><h2 className="gw-section">Revisiones y bloqueos</h2><TaskList tasks={[...totals.reviews,...totals.blocked]} onPick={pick}/><h2 className="gw-section">Cambios desde tu última entrada</h2><Activity rows={data.audit.filter(x=>new Date(x.created_at).getTime()>lastVisit)}/><h2 className="gw-section">Carga por persona</h2><div className="gw-list">{data.members.map(m=><article key={m.user_id}><strong>{m.display_name}</strong><p>{data.tasks.filter(t=>t.responsible_id===m.user_id&&!['published','archived'].includes(t.state)).length} entregables activos</p></article>)}</div></>}
 {tab==='projects'&&<><h2>Productos y microediciones</h2>{permissions['project.create']&&<CommandForm busy={disabled} button="Crear proyecto" fields={{title:'Nombre del proyecto',brief:{label:'Brief principal',type:'textarea'},starts_at:{label:'Inicio',type:'datetime-local',optional:true},ends_at:{label:'Cierre',type:'datetime-local',optional:true}}} onSave={d=>command('project.create',d)}/>}<div className="gw-list">{data.projects.map(p=><article key={p.id}><div className="gw-row"><h3>{p.title}</h3><span className="gw-badge">{p.status}</span></div><p>{p.brief||'Sin brief todavía'}</p><p>{dateLabel(p.starts_at)} → {dateLabel(p.ends_at)}</p><p>{data.tasks.filter(t=>t.project_id===p.id&&['published','archived'].includes(t.state)).length}/{data.tasks.filter(t=>t.project_id===p.id).length} entregables publicados o archivados</p><button onClick={()=>{setProjectId(p.id);setTab('tasks');}}>Abrir proyecto</button></article>)}</div>{project&&permissions['project.update']&&<CommandForm key={project.id+project.revision} initial={project} busy={disabled} button="Guardar proyecto" fields={{title:'Nombre',brief:{label:'Brief',type:'textarea'},status:{label:'Estado',options:{planned:'Planeado',active:'Activo',closed:'Cerrado',...(permissions['project.archive']?{archived:'Archivado'}:{})}},starts_at:{label:'Inicio',type:'datetime-local',optional:true},ends_at:{label:'Cierre',type:'datetime-local',optional:true}}} onSave={d=>command('project.save',d,project.revision)}/>}</>}
 {tab==='tasks'&&<><h2>{project?.title||'Entregables'}</h2>{project&&<CommandForm busy={disabled} button="Crear entregable" fields={{title:'Título',description:{label:'Descripción',type:'textarea',optional:true},area_id:{label:'Área',options:choices(data.areas.filter(a=>a.project_id===projectId),'name')},responsible_id:{label:'Responsable',options:choices(data.members,'display_name'),optional:true}}} onSave={d=>command('task.create',d)}/>}<div className="gw-grid"><TaskList tasks={data.tasks.filter(t=>t.project_id===projectId)} onPick={pick} selectedId={selectedId}/>{task?<TaskDetail key={task.id} task={task} data={data} command={command} busy={disabled} previewMode={previewMode}/>:<p className="gw-empty">Selecciona un entregable para trabajar o revisar.</p>}</div></>}
 {tab==='calendar'&&<><h2>Fechas del proyecto</h2><p>Las entregas reflejan la fecha registrada en cada entregable.</p>{project&&permissions['task.update_schedule']&&<CommandForm busy={disabled} button="Añadir hito" fields={{title:'Título',kind:{label:'Tipo',options:{milestone:'Hito',review:'Revisión',editorial:'Fecha editorial'}},starts_at:{label:'Inicio',type:'datetime-local'},ends_at:{label:'Fin',type:'datetime-local',optional:true}}} onSave={d=>command('event.save',d)}/>}<div className="gw-list">{data.events.filter(e=>e.project_id===projectId).sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at)).map(e=><article key={e.id}><h3>{e.title}</h3><p>{dateLabel(e.starts_at)} · {e.kind}</p>{e.deliverable_id&&<button onClick={()=>{setSelectedId(e.deliverable_id);setTab('tasks');}}>Abrir entregable</button>}{e.kind!=='deadline'&&permissions['task.update_schedule']&&<CommandForm busy={disabled} initial={e} button="Actualizar hito" fields={{title:'Título',kind:{label:'Tipo',options:{milestone:'Hito',review:'Revisión',editorial:'Fecha editorial'}},starts_at:{label:'Inicio',type:'datetime-local'},ends_at:{label:'Fin',type:'datetime-local',optional:true}}} onSave={d=>command('event.save',{...d,id:e.id},e.revision)}/>}</article>)}</div></>}
 {tab==='team'&&<TeamPanel data={data} permissions={permissions} command={command} busy={disabled} unitId={unitId} projectId={projectId}/>}{tab==='audit'&&<><h2>Actividad de Workspace</h2>{permissions['audit.export_full']&&<button disabled={disabled} onClick={async()=>{try{const result=await rpc('workspace_export_audit',{p_unit:unitId});const blob=new Blob([JSON.stringify(result,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='auditoria-workspace.json';anchor.click();URL.revokeObjectURL(url);}catch(e){setNotice(e.message);}}}>Exportar auditoría completa</button>}<p>Últimas 200 acciones visibles según tu alcance.</p><Activity rows={data.audit}/></>}
 </>}
 </main></div>;
}
