import React, { useEffect, useState } from 'react';
import { ArrowUpRight, Check, Globe2, Plus, Save, Users, X } from 'lucide-react';
import { useNetworkWorkspace, networkRpc } from '../../hooks/useNetworkServers';
import PartnerEmblem from '../network/PartnerEmblem';
import { EDITIONS, EMPTY_SERVER, GAME_STATUS, PLACEMENTS, REVIEW_STATUS, serverPayload, STYLES, safeUrl } from '../../network/serverData';
import { uploadToCloudinary } from '../../cloudinary';
import NetworkReport from '../network/NetworkReport';
import '../network/network.css';

function ServerTeam({server,userId,previewMode}){
  const [members,setMembers]=useState([]);const [handle,setHandle]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const refresh=async()=>{try{setMembers(previewMode?[{user_id:'preview-owner',handle:'tu-gba-id',role:'owner'}]:await networkRpc('vista_network_team',{p_server_id:server.id}));}catch(e){setError(e.message);}};
  useEffect(()=>{void refresh();},[server.id,previewMode]);
  const change=async(name,remove=false)=>{
    setBusy(true);setError('');
    try{if(previewMode)setMembers(current=>remove?current.filter(m=>m.handle!==name):[...current,{handle:name.replace(/^@/,''),role:'admin',user_id:name}]);else{await networkRpc('vista_manage_network_member',{p_server_id:server.id,p_handle:name,p_remove:remove});await refresh();}setHandle('');}
    catch(e){setError(e.message);}finally{setBusy(false);}
  };
  return <section className="border-t border-[#d2d2d7] pt-7 mt-8"><h3 className="font-bold text-sm flex items-center gap-2"><Users size={16}/>Administración del servidor</h3><p className="vn-note">Cada administrador utiliza su propio GBA ID para editar la ficha y consultar sus resultados.</p>{error&&<p role="alert" className="text-red-600 text-xs mt-3">{error}</p>}<div className="mt-4 divide-y divide-[#d2d2d7]">{members.map(m=><div key={m.user_id} className="flex items-center py-3 gap-3 text-xs"><strong>@{m.handle}</strong><span className="text-[#86868b]">{m.role==='owner'?'Propietario':'Administrador'}</span>{server.owner_id===userId&&m.role!=='owner'&&<button aria-label={`Retirar a ${m.handle}`} className="ml-auto p-2" disabled={busy} onClick={()=>change(m.handle,true)}><X size={14}/></button>}</div>)}</div>{server.owner_id===userId&&<form onSubmit={e=>{e.preventDefault();void change(handle);}} className="mt-4 flex gap-3"><input className="vn-input" aria-label="GBA ID del administrador" placeholder="@GBA_ID" value={handle} onChange={e=>setHandle(e.target.value)} required/><button className="vn-button" disabled={busy}><Plus size={14}/>Agregar</button></form>}</section>;
}
export default function NetworkServerStudio({userId,previewMode=false}){
  const {servers,loading,error,refresh,save}=useNetworkWorkspace(previewMode);
  const [id,setId]=useState('');const [form,setForm]=useState({...EMPTY_SERVER});const [busy,setBusy]=useState(false);const [notice,setNotice]=useState(null);const [files,setFiles]=useState({});const [placement,setPlacement]=useState('both');const [requested,setRequested]=useState(false);
  const selected=servers.find(s=>s.id===id)||null;
  useEffect(()=>{if(!id&&servers.length)setId(servers[0].id);},[servers,id]);
  useEffect(()=>{setForm(selected?serverPayload(selected):{...EMPTY_SERVER});setFiles({});setRequested(Boolean(selected?.partner_interest));},[selected]);
  const field=(name,value)=>setForm(current=>({...current,[name]:value}));
  const submit=async event=>{
    event.preventDefault();setBusy(true);setNotice(null);
    try{
      const payload={...form};
      for(const [key,file]of Object.entries(files)){if(!file)continue;const url=await uploadToCloudinary(file,`VISTA_Network_Servers/${selected?.slug||userId}`);if(!url)throw new Error('No se pudo subir la imagen. Inténtalo de nuevo.');payload[key]=url;}
      const next=await save(selected?.id,payload);setId(next.id);setNotice({type:'success',text:'Ficha guardada. Puedes consultar su estado de revisión en Studio.'});
    }catch(e){setNotice({type:'error',text:e.message||'No se pudo guardar la ficha.'});}finally{setBusy(false);}
  };
  const requestPartner=async()=>{setBusy(true);setNotice(null);try{if(!previewMode)await networkRpc('vista_request_network_partner',{p_server_id:selected.id,p_placement:placement});setRequested(true);setNotice({type:'success',text:'Interés registrado. GBA podrá acordar contigo la tarifa, el periodo y los entregables antes de activar el patrocinio.'});}catch(e){setNotice({type:'error',text:e.message});}finally{setBusy(false);}};
  if(loading)return <p className="text-sm text-[#86868b] py-12" role="status">Abriendo tus servidores…</p>;
  if(error)return <div className="vn-error">{error}<button className="vn-button vn-button-quiet mt-4" onClick={refresh}>Reintentar</button></div>;
  return <div className="vn bg-transparent"><div className="flex items-center gap-3 flex-wrap mb-7"><Globe2 size={21}/><h2 className="font-bold text-lg">Tus servidores</h2>{servers.length>0&&<select className="vn-input max-w-xs sm:ml-auto" aria-label="Seleccionar servidor" value={id} onChange={e=>setId(e.target.value)}>{servers.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}{id==='new'&&<option value="new">Nueva ficha</option>}</select>}<button className="vn-button vn-button-quiet" onClick={()=>{setId('new');setForm({...EMPTY_SERVER});setNotice(null);}}><Plus size={15}/>Nueva ficha</button></div>
    {notice&&<p role={notice.type==='error'?'alert':'status'} className={notice.type==='error'?'vn-error mb-6':'vn-alert mb-6'}>{notice.text}</p>}
    <div className="grid lg:grid-cols-[minmax(0,1fr)_300px] gap-8"><div><form onSubmit={submit} className="bg-white border border-[#d2d2d7] rounded-md p-6 md:p-8"><header className="border-b border-[#d2d2d7] pb-5 mb-6"><p className="vn-eyebrow text-[#86868b]">Ficha gratuita · Piloto Network</p><h3 className="font-serif text-3xl mt-3">{selected?selected.nombre:'Un lugar para tu comunidad.'}</h3><p className="vn-note">Describe tu servidor y cómo pueden participar los jugadores. Las fichas y sus cambios pasan por revisión.</p>{selected&&<span className="inline-block text-xs font-bold mt-3 px-3 py-2 bg-[#edf4ff] rounded">{REVIEW_STATUS[selected.estado]}</span>}{selected?.review_notes&&<p className="vn-note">Revisión: {selected.review_notes}</p>}</header>
      <div className="grid sm:grid-cols-2 gap-5"><label className="sm:col-span-2"><span className="vn-eyebrow block mb-2">Nombre del servidor</span><input className="vn-input" value={form.nombre} onChange={e=>field('nombre',e.target.value)} minLength={2} maxLength={80} required/></label><label className="sm:col-span-2"><span className="vn-eyebrow block mb-2">Una frase para presentarlo</span><input className="vn-input" value={form.headline} onChange={e=>field('headline',e.target.value)} maxLength={160} placeholder="Qué hace especial a tu comunidad"/></label><label className="sm:col-span-2"><span className="vn-eyebrow block mb-2">Descripción</span><textarea className="vn-input" value={form.descripcion} onChange={e=>field('descripcion',e.target.value)} rows={5} minLength={20} maxLength={1600} required/></label>
      {[['ip','Dirección IP','play.tuservidor.com',160],['version','Versión','1.21',60],['idioma','Idioma','Español',60],['region','Comunidad o región','Latinoamérica, global…',80]].map(([key,label,placeholder,max])=><label key={key}><span className="vn-eyebrow block mb-2">{label}</span><input className="vn-input" value={form[key]} onChange={e=>field(key,e.target.value)} placeholder={placeholder} maxLength={max} required={key==='idioma'}/></label>)}
      {[['edition','Edición',EDITIONS],['estilo','Enfoque',Object.fromEntries(STYLES.map(s=>[s,s]))],['game_status','Estado del servidor',GAME_STATUS]].map(([key,label,options])=><label key={key}><span className="vn-eyebrow block mb-2">{label}</span><select className="vn-input" value={form[key]} onChange={e=>field(key,e.target.value)}>{Object.entries(options).map(([value,name])=><option key={value} value={value}>{name}</option>)}</select></label>)}
      {[['discord_url','Discord'],['website_url','Sitio web'],['map_url','Mapa del servidor']].map(([key,label])=><label key={key} className="sm:col-span-2"><span className="vn-eyebrow block mb-2">{label}</span><input className="vn-input" type="url" pattern="https://.*" value={form[key]} onChange={e=>field(key,e.target.value)} placeholder="https://…" maxLength={2000}/></label>)}
      {[['logo_url','Logo'],['portada_url','Portada']].map(([key,label])=><label key={key}><span className="vn-eyebrow block mb-2">{label}</span>{safeUrl(form[key])&&<img className="h-24 w-full object-cover rounded mb-3" src={safeUrl(form[key])} alt={label}/>}<input className="vn-input mb-2" type="url" pattern="https://.*" value={form[key]} onChange={e=>field(key,e.target.value)} placeholder="URL HTTPS de la imagen" maxLength={2000}/><input className="text-xs w-full" aria-label={`Subir ${label.toLowerCase()}`} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setFiles(current=>({...current,[key]:e.target.files?.[0]}))}/></label>)}</div>
      <p className="vn-note">Incluye una IP o un enlace de Discord para que los jugadores puedan conocer tu comunidad.</p><button className="vn-button mt-6" disabled={busy}><Save size={15}/>{busy?'Guardando…':selected?'Guardar cambios':'Enviar ficha a revisión'}</button>
    </form>{selected&&<><div className="bg-[#f5f5f7] border border-[#d2d2d7] p-6 mt-6 rounded-md"><NetworkReport serverId={selected.id} previewMode={previewMode}/></div><ServerTeam server={selected} userId={userId} previewMode={previewMode}/></>}</div>
    <aside className="self-start bg-[#f5f5f7] rounded-md border border-[#d2d2d7] p-6"><PartnerEmblem size={42}/><p className="vn-eyebrow mt-5">GBA Partners</p><h3 className="font-serif text-3xl mt-3">Tu servidor,<br/>en primer plano.</h3><p className="vn-note">Promoción pagada por un periodo acordado. Un espacio destacado en el directorio, un hero de pantalla completa o ambos.</p><div className="mt-6 space-y-3 text-xs text-[#6e6e73]">{['Vigencia definida','Entregables acordados','Reporte de actividad'].map(text=><p className="flex items-center gap-2" key={text}><Check size={14}/>{text}</p>)}</div><label className="block mt-6"><span className="vn-eyebrow block mb-2">Me interesa</span><select className="vn-input" value={placement} onChange={e=>setPlacement(e.target.value)}>{Object.entries(PLACEMENTS).map(([key,value])=><option value={key} key={key}>{value}</option>)}</select></label><button className="vn-button mt-4 w-full" disabled={!selected||busy} onClick={requestPartner}>{requested?'Actualizar interés':'Solicitar información'}<ArrowUpRight size={14}/></button><p className="vn-note">{selected?'Registrar tu interés no activa un cobro ni un patrocinio. GBA acordará las condiciones contigo.':'Guarda primero la ficha de tu servidor para registrar tu interés.'}</p></aside></div>
  </div>;
}
