import React, { useEffect, useState } from 'react';
import { ArrowUpRight, Check, Globe2, Plus, Save, Users, X } from 'lucide-react';
import { useNetworkWorkspace, networkRpc } from '../../hooks/useNetworkServers';
import {useAuth} from '../../context/AuthContext';
import {profileLink} from '../../studios/studioData';
import PartnerEmblem from '../network/PartnerEmblem';
import { ACCESS_TYPES, EDITIONS, EMPTY_SERVER, GAME_STATUS, PLACEMENTS, REVIEW_STATUS, serverPayload, STYLES, safeUrl } from '../../network/serverData';
import { uploadToCloudinary } from '../../cloudinary';
import NetworkReport from '../network/NetworkReport';
import NetworkImageInput from '../network/NetworkImageInput';
import '../network/network.css';

function ServerTeam({server,userId,previewMode}){
  const [members,setMembers]=useState([]);const [handle,setHandle]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const refresh=async()=>{try{setMembers(previewMode?[{user_id:'preview-owner',handle:'tu-gba-id',role:'owner'}]:await networkRpc('vista_network_team',{p_server_id:server.id}));}catch(e){setError(e.message);}};
  useEffect(()=>{void refresh();},[server.id,previewMode]);
  const change=async(name,remove=false)=>{
    setBusy(true);setError('');
    try{if(previewMode)setMembers(current=>remove?current.filter(m=>m.handle!==name):[...current,{handle:name.replace(/^@/,''),role:'admin',user_id:name}]);else{await networkRpc('vista_manage_network_member',{p_server_id:server.id,p_handle:name,p_remove:remove});await refresh();}setHandle('');}
    catch(e){setError(e.message);}finally{setBusy(false);}
  };
  return <section className="border-t border-[#d2d2d7] pt-7 mt-8"><h3 className="font-bold text-sm flex items-center gap-2"><Users size={16}/>Administración del servidor</h3><p className="vn-note">Cada administrador utiliza su propio GBA ID para editar la ficha y consultar sus resultados.</p>{error&&<p role="alert" className="text-red-600 text-xs mt-3">{error}</p>}<div className="mt-4 divide-y divide-[#d2d2d7]">{members.map(m=><div key={m.user_id} className="flex items-center py-3 gap-3 text-xs"><a className="vn-link" href={profileLink(m.handle)}> @{m.handle}</a><span className="text-[#86868b]">{m.role==='owner'?'Propietario':'Administrador'}</span>{server.owner_id===userId&&m.role!=='owner'&&<button aria-label={`Retirar a ${m.handle}`} className="ml-auto p-2" disabled={busy} onClick={()=>change(m.handle,true)}><X size={14}/></button>}</div>)}</div>{server.owner_id===userId&&<form onSubmit={e=>{e.preventDefault();void change(handle);}} className="mt-4 flex gap-3"><input className="vn-input" aria-label="GBA ID del administrador" placeholder="@GBA_ID" value={handle} onChange={e=>setHandle(e.target.value)} required/><button className="vn-button" disabled={busy}><Plus size={14}/>Agregar</button></form>}</section>;
}
export default function NetworkServerStudio({userId,previewMode=false}){
  const {user}=useAuth();
  const [studios,setStudios]=useState([]),[studioError,setStudioError]=useState(''),[developerType,setDeveloperType]=useState('none');
  useEffect(()=>{if(previewMode)return;let active=true;networkRpc('vista_studios_workspace').then(data=>{if(active)setStudios(data.studios.filter(s=>['owner','admin'].includes(s.role)));}).catch(()=>{if(active)setStudioError('No pudimos abrir tus estudios. Puedes guardar el resto de la ficha y volver a intentarlo después.');});return()=>{active=false;};},[previewMode]);
  const {servers,loading,error,refresh,save}=useNetworkWorkspace(previewMode);
  const [id,setId]=useState('');const [form,setForm]=useState({...EMPTY_SERVER});const [busy,setBusy]=useState(false);const [notice,setNotice]=useState(null);const [files,setFiles]=useState({});const [placement,setPlacement]=useState('both');const [requested,setRequested]=useState(false);const [progress,setProgress]=useState('');
  const selected=servers.find(s=>s.id===id)||null;
  useEffect(()=>{if(!id&&servers.length&&Object.keys(EMPTY_SERVER).every(key=>form[key]===EMPTY_SERVER[key])&&!Object.values(files).some(Boolean))setId(servers[0].id);},[servers,id]);
  // Reload the draft only when choosing another server, not when its list refreshes.
  useEffect(()=>{setForm(selected?serverPayload(selected):{...EMPTY_SERVER});setFiles({});setDeveloperType(selected?.developer_studio_id?'studio':selected?.developer_handle?'person':'none');setRequested(Boolean(selected?.partner_interest));},[id]);
  const field=(name,value)=>setForm(current=>({...current,[name]:value}));
  const submit=async event=>{
    event.preventDefault();if(busy)return;setBusy(true);setNotice(null);
    try{
      const payload=Object.fromEntries(Object.entries(form).map(([key,value])=>[key,typeof value==='string'?value.trim():value]));
      for(const [key,file]of Object.entries(files)){if(!file)continue;setProgress(`Subiendo ${key==='logo_url'?'logo':'portada'}…`);const url=previewMode?await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('No se pudo leer la imagen.'));reader.readAsDataURL(file);}):await uploadToCloudinary(file,`VISTA_Network_Servers/${selected?.slug||userId}`);if(!url)throw new Error('No se pudo subir la imagen. Inténtalo de nuevo.');payload[key]=url;field(key,url);setFiles(current=>({...current,[key]:null}));}
      setProgress('Guardando ficha…');
      const next=await save(selected?.id,payload);setId(next.id);setForm(serverPayload(next));setNotice({type:'success',text:'Ficha guardada. Puedes consultar su estado de revisión en Studio.'});
    }catch(e){setNotice({type:'error',text:e.message||'No se pudo guardar la ficha.'});}finally{setBusy(false);setProgress('');}
  };
  const requestPartner=async()=>{setBusy(true);setNotice(null);try{if(!previewMode)await networkRpc('vista_request_network_partner',{p_server_id:selected.id,p_placement:placement});setRequested(true);setNotice({type:'success',text:'Interés registrado. GBA podrá acordar contigo la tarifa, el periodo y los entregables antes de activar el patrocinio.'});}catch(e){setNotice({type:'error',text:e.message});}finally{setBusy(false);}};
  if(loading)return <p className="text-sm text-[#86868b] py-12" role="status">Abriendo tus servidores…</p>;
  return <div className="vn bg-transparent"><div className="flex items-center gap-3 flex-wrap mb-7"><Globe2 size={21}/><h2 className="font-bold text-lg">Tus servidores</h2>{servers.length>0&&<select className="vn-input max-w-xs sm:ml-auto" aria-label="Seleccionar servidor" disabled={busy} value={id} onChange={e=>setId(e.target.value)}>{servers.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}{!selected&&<option value={id}>Nueva ficha</option>}</select>}<button className="vn-button vn-button-quiet" disabled={busy} onClick={()=>{setId('new');setForm({...EMPTY_SERVER});setFiles({});setDeveloperType('none');setRequested(false);setNotice(null);}}><Plus size={15}/>Nueva ficha</button></div>
    {error&&<div className="vn-error mb-6" role="alert">{error}<button type="button" className="vn-button vn-button-quiet mt-4" disabled={busy} onClick={refresh}>Reintentar</button></div>}
    {notice&&<p role={notice.type==='error'?'alert':'status'} className={notice.type==='error'?'vn-error fixed bottom-6 right-6 z-50 max-w-[calc(100vw-3rem)] sm:max-w-md shadow-xl':'vn-alert fixed bottom-6 right-6 z-50 max-w-[calc(100vw-3rem)] sm:max-w-md shadow-xl'}>{notice.text}<button type="button" className="block mt-3 underline text-xs" onClick={()=>setNotice(null)}>Entendido</button></p>}
    <div className="grid lg:grid-cols-[minmax(0,1fr)_300px] gap-8"><div><form onSubmit={submit} className="bg-white border border-[#d2d2d7] rounded-md p-6 md:p-8"><fieldset disabled={busy} className="min-w-0"><header className="border-b border-[#d2d2d7] pb-5 mb-6"><p className="vn-eyebrow text-[#86868b]">Ficha gratuita · Piloto Network</p><h3 className="font-serif text-3xl mt-3">{selected?selected.nombre:'Un lugar para tu comunidad.'}</h3><p className="vn-note">Describe tu servidor y cómo pueden participar los jugadores. Las fichas y sus cambios pasan por revisión.</p>{selected&&<span className="inline-block text-xs font-bold mt-3 px-3 py-2 bg-[#edf4ff] rounded">{REVIEW_STATUS[selected.estado]}</span>}{selected?.review_notes&&<p className="vn-note">Revisión: {selected.review_notes}</p>}</header>
      <div className="grid sm:grid-cols-2 gap-5"><label className="sm:col-span-2"><span className="vn-eyebrow block mb-2">Nombre del servidor</span><input className="vn-input" value={form.nombre} onChange={e=>field('nombre',e.target.value)} minLength={2} maxLength={80} required/></label><label className="sm:col-span-2"><span className="vn-eyebrow block mb-2">Una frase para presentarlo</span><input className="vn-input" value={form.headline} onChange={e=>field('headline',e.target.value)} maxLength={160} placeholder="Qué hace especial a tu comunidad"/></label><label className="sm:col-span-2"><span className="vn-eyebrow block mb-2">Descripción</span><textarea className="vn-input" value={form.descripcion} onChange={e=>field('descripcion',e.target.value)} rows={5} minLength={20} maxLength={1600} required/></label>
      <label className="sm:col-span-2"><span className="vn-eyebrow block mb-2">Cómo entrar al servidor</span><select className="vn-input" value={form.access_type} onChange={e=>field('access_type',e.target.value)}>{Object.entries(ACCESS_TYPES).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label>
      {form.access_type!=='direct'&&<label className="sm:col-span-2"><span className="vn-eyebrow block mb-2">{form.access_type==='modpack'?'Enlace al modpack':'Enlace de invitación o solicitud'}</span><input className="vn-input" type="url" pattern="https://.*" required value={form.access_url} onChange={e=>field('access_url',e.target.value)} maxLength={2000}/></label>}
      <label className="sm:col-span-2"><span className="vn-eyebrow block mb-2">Instrucciones de acceso · Opcional</span><textarea className="vn-input" rows={3} value={form.access_instructions} onChange={e=>field('access_instructions',e.target.value)} maxLength={1200} placeholder="Instala el modpack y utiliza el servidor que viene incluido…"/></label>
      {[['ip','Dirección IP','play.tuservidor.com',160],['version','Versión','1.21',60],['idioma','Idioma','Español',60],['region','Comunidad o región','Latinoamérica, global…',80]].map(([key,label,placeholder,max])=><label key={key}><span className="vn-eyebrow block mb-2">{label}</span><input className="vn-input" value={form[key]} onChange={e=>field(key,e.target.value)} placeholder={placeholder} maxLength={max} required={key==='idioma'||(key==='ip'&&form.access_type==='direct')}/></label>)}
      {[['edition','Edición',EDITIONS],['estilo','Enfoque',Object.fromEntries(STYLES.map(s=>[s,s]))],['game_status','Estado del servidor',GAME_STATUS]].map(([key,label,options])=><label key={key}><span className="vn-eyebrow block mb-2">{label}</span><select className="vn-input" value={form[key]} onChange={e=>field(key,e.target.value)}>{Object.entries(options).map(([value,name])=><option key={value} value={value}>{name}</option>)}</select></label>)}
      {[['discord_url','Discord'],['website_url','Sitio web'],['map_url','Mapa del servidor'],['support_url','Enlace para apoyar el proyecto (Patreon, etc.)']].map(([key,label])=><label key={key} className="sm:col-span-2"><span className="vn-eyebrow block mb-2">{label}</span><input className="vn-input" type="url" pattern="https://.*" value={form[key]} onChange={e=>field(key,e.target.value)} placeholder="https://…" maxLength={2000}/></label>)}
      <section className="sm:col-span-2 border-t border-[#d2d2d7] pt-5"><h4 className="font-semibold text-sm">Quién lo desarrolla</h4><p className="vn-note">Reconoce a una persona con GBA ID o a un estudio. La atribución no cambia los permisos de administración.</p>{studioError&&<p className="vn-note" role="alert">{studioError}</p>}<label className="block mt-4"><span className="vn-eyebrow block mb-2">Desarrollado por</span><select className="vn-input" value={developerType} onChange={e=>{setDeveloperType(e.target.value);field('developer_studio_id','');field('developer_handle','');}}><option value="none">Todavía sin indicar</option><option value="person">Una persona</option><option value="studio">Un estudio</option></select></label>
      {developerType==='person'&&<label className="block mt-4"><span className="vn-eyebrow block mb-2">GBA ID del desarrollador</span><div className="flex gap-3"><input className="vn-input" placeholder="@nombre" value={form.developer_handle} onChange={e=>field('developer_handle',e.target.value)} required/><button type="button" className="vn-button vn-button-quiet" onClick={()=>field('developer_handle',user?.nombre||'')}>Soy yo</button></div><p className="vn-note">Si es otra persona, recibirá una solicitud para confirmar su participación. {selected?.developer_status==='pending'?'Confirmación pendiente.':selected?.developer_status==='declined'?'La persona rechazó la atribución; selecciona otro desarrollador.':''}</p></label>}
      {developerType==='studio'&&<label className="block mt-4"><span className="vn-eyebrow block mb-2">Estudio</span><select className="vn-input" value={form.developer_studio_id} onChange={e=>field('developer_studio_id',e.target.value)} required><option value="">Selecciona un estudio que administras</option>{form.developer_studio_id&&!studios.some(s=>s.id===form.developer_studio_id)&&<option value={form.developer_studio_id}>Estudio vinculado</option>}{studios.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select><a href="/?workspace=studios" className="vn-link text-xs mt-4" target="_blank" rel="noopener noreferrer">Registrar o administrar un estudio gratis<ArrowUpRight size={13}/></a></label>}</section>
      {[['logo_url','Logo'],['portada_url','Portada']].map(([key,label])=><NetworkImageInput previewMode={previewMode} key={key} label={label} value={form[key]} file={files[key]} onFileChange={file=>setFiles(current=>({...current,[key]:file}))} onUrlChange={value=>field(key,value)} logo={key==='logo_url'} hint={key==='logo_url'?'Se recomienda una imagen cuadrada.':'Se recomienda una imagen horizontal de 16:9.'}/>)}</div>
      <p className="vn-note">Puedes compartir la IP, un modpack con el servidor incluido o un enlace de invitación. Los enlaces de apoyo llevan a una plataforma externa.</p><button className="vn-button mt-6" disabled={busy}><Save size={15}/>{busy?progress||'Guardando…':selected?'Guardar cambios':'Enviar ficha a revisión'}</button></fieldset><p role="status" className="vn-note">{busy?progress:'Las imágenes elegidas se suben a Cloudinary al guardar la ficha.'}</p>
    </form>{selected&&<><div className="bg-[#f5f5f7] border border-[#d2d2d7] p-6 mt-6 rounded-md"><NetworkReport serverId={selected.id} previewMode={previewMode}/></div><ServerTeam server={selected} userId={userId} previewMode={previewMode}/></>}</div>
    <aside className="self-start bg-[#f5f5f7] rounded-md border border-[#d2d2d7] p-6"><PartnerEmblem size={42}/><p className="vn-eyebrow mt-5">GBA Partners</p><h3 className="font-serif text-3xl mt-3">Tu servidor,<br/>en primer plano.</h3><p className="vn-note">Promoción pagada por un periodo acordado. Un espacio destacado en el directorio, un hero de pantalla completa o ambos.</p><div className="mt-6 space-y-3 text-xs text-[#6e6e73]">{['Vigencia definida','Entregables acordados','Reporte de actividad'].map(text=><p className="flex items-center gap-2" key={text}><Check size={14}/>{text}</p>)}</div><label className="block mt-6"><span className="vn-eyebrow block mb-2">Me interesa</span><select className="vn-input" value={placement} onChange={e=>setPlacement(e.target.value)}>{Object.entries(PLACEMENTS).map(([key,value])=><option value={key} key={key}>{value}</option>)}</select></label><button className="vn-button mt-4 w-full" disabled={!selected||busy} onClick={requestPartner}>{requested?'Actualizar interés':'Solicitar información'}<ArrowUpRight size={14}/></button><p className="vn-note">{selected?'Registrar tu interés no activa un cobro ni un patrocinio. GBA acordará las condiciones contigo.':'Guarda primero la ficha de tu servidor para registrar tu interés.'}</p></aside></div>
  </div>;
}
